In [1]:
import pandas as pd
import numpy as np

In [2]:
update = pd.read_csv('UPDATE.csv')
update.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'appl_id', 'inventor_name_first',
       'inventor_name_middle', 'inventor_name_last', 'inventor_rank',
       'inventor_region_code', 'inventor_country_code',
       'inventor_country_name', 'inventor_address_type', '_merge',
       'duplicates', 'full_name', 'first_last_name', 'state', 'appl_id.1',
       'Unnamed: 17', 'linkedinProfile', 'Maybe'],
      dtype='object')

In [4]:
update['inventor_name_first'] = update['inventor_name_first'].str.title()
update['inventor_name_middle'] = update['inventor_name_middle'].str.title()
update['inventor_name_last'] = update['inventor_name_last'].str.title()
update['full_name'] = update['full_name'].str.title()
update['first_last_name'] = update['first_last_name'].str.title()

In [11]:
update = update.drop(['duplicates'], axis = 1)

In [15]:
update["Duplicates"]  = update.duplicated(subset = ['full_name', 'state'], keep = False)

In [17]:
update["Duplicates"] = update["Duplicates"] * 1

In [19]:
update.to_csv('UPDATE.csv')

In [2]:
test = pd.read_csv('final copy.csv', sep = ',')

In [26]:
dupes = len(update[update["Duplicates"] == 0])
print(dupes)

1592

In [33]:
update["Duplicates"]  = update.duplicated(subset = ['full_name', 'state'], keep = False)
update["unique"] = update.duplicated(subset = ['full_name', 'state'], keep = "first")

update["Duplicates"] = update["Duplicates"] * 1
update['unique'] = update['unique'] * 1

In [34]:
update.to_csv("UPDATE.csv")

In [3]:
test.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'appl_id', 'inventor_name_first',
       'inventor_name_middle', 'inventor_name_last', 'inventor_rank',
       'inventor_region_code', 'inventor_country_code',
       'inventor_country_name', 'inventor_address_type', '_merge',
       'duplicates', 'full_name', 'first_last_name', 'state', 'appl_id.1',
       'Unnamed: 17', 'linkedinProfile', 'Maybe'],
      dtype='object')

In [17]:
sub = test[test['duplicates'] == False]
# replace NaN with empty strings
sub = sub.replace(np.nan, '', regex = True)

sub2 = sub[sub['linkedinProfile'] == 'None']
sub3 = sub[sub['linkedinProfile'] == ""]
len(sub2)
len(sub3)

print(len(sub) - len(sub2) - len(sub3))

925

In [19]:
sub.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'appl_id', 'inventor_name_first',
       'inventor_name_middle', 'inventor_name_last', 'inventor_rank',
       'inventor_region_code', 'inventor_country_code',
       'inventor_country_name', 'inventor_address_type', '_merge',
       'duplicates', 'full_name', 'first_last_name', 'state', 'appl_id.1',
       'Unnamed: 17', 'linkedinProfile', 'Maybe'],
      dtype='object')

In [74]:
dupes = sub.duplicated(subset = ['inventor_name_last','inventor_name_first','inventor_region_code'],keep=False)

In [25]:
fix = pd.concat([sub, dupes], axis=1)

In [31]:
fix = fix.drop(['duplicates'], axis = 1)

In [46]:
fix = fix.drop(['Unnamed: 0'], axis = 1)
fix = fix.drop(['Unnamed: 17'], axis = 1)
fix = fix.drop(['appl_id.1'], axis = 1)

In [56]:
fix.columns

Index(['Original Index', 'appl_id', 'inventor_name_first',
       'inventor_name_middle', 'inventor_name_last', 'inventor_rank',
       'inventor_region_code', 'inventor_country_code',
       'inventor_country_name', 'inventor_address_type', '_merge', 'full_name',
       'first_last_name', 'state', 'linkedinProfile', 'Maybe', 'Duplicates'],
      dtype='object')

In [35]:
fix = fix.rename({'Unnamed: 0.1':'Original Index'}, axis = 1)

In [52]:
fix = fix.rename({0:'Duplicates'}, axis = 1)

In [55]:
fix.Duplicates = fix.Duplicates.astype(int)

In [57]:
fix.to_csv('updated_urls.csv', sep = ',')

In [59]:
china = fix[fix['inventor_country_code'] == "CN"]
print(len(china))

In [61]:
taiwan = fix[fix['inventor_country_code'] == "TW"]
print(len(taiwan))

In [63]:
non_dupes = fix[fix['Duplicates'] == 1]

In [64]:
len(non_dupes)

32

In [70]:
fix['inventor_name_first'] = fix['inventor_name_first'].str.title()
fix['inventor_name_middle'] = fix['inventor_name_middle'].str.title()
fix['inventor_name_last'] = fix['inventor_name_last'].str.title()
fix['full_name'] = fix['full_name'].str.title()
fix['first_last_name'] = fix['first_last_name'].str.title()

In [71]:
fix

,Original Index,appl_id,inventor_name_first,inventor_name_middle,inventor_name_last,inventor_rank,inventor_region_code,inventor_country_code,inventor_country_name,inventor_address_type,_merge,full_name,first_last_name,state,linkedinProfile,Maybe,Duplicates
0,0,13199870,Durand,Kevin,Dickerson,1,KS,US,UNITED STATES,residence,matched (3),Durand Kevin Dickerson,Durand Dickerson,Kansas,https://www.linkedin.com/in/durand-dickerson-b...,,0
1,2,13199870,Lawrence,Derwood,Kenemore,2,KS,US,UNITED STATES,residence,matched (3),Lawrence Derwood Kenemore,Lawrence Kenemore,Kansas,https://www.linkedin.com/in/larry-kenemore-jr-...,,0
2,3,13261475,Stefanos,,Ntoukolianos,1,,GR,GREECE,postal,matched (3),Stefanos Ntoukolianos,Stefanos Ntoukolianos,,None,,0
3,5,13261723,Mukul,Chandra,Gope,1,,IN,INDIA,postal,matched (3),Mukul Chandra Gope,Mukul Gope,,None,,0
4,7,13261789,Mitsutoshi,,Sugawara,1,,JP,JAPAN,postal,matched (3),Mitsutoshi Sugawara,Mitsutoshi Sugawara,,https://www.linkedin.com/in/mitsutoshi-sugawar...,,0
5,9,13261809,Georgios,,Mavroeidis,1,,GR,GREECE,residence,matched (3),Georgios Mavroeidis,Georgios Mavroeidis,,https://www.linkedin.com/in/georgios-mavroeidi...,,0
6,11,13261831,Lorena,,Dordan,1,CA,US,UNITED STATES,residence,matched (3),Lorena Dordan,Lorena Dordan,California,https://www.linkedin.com/in/lorena-dordan-a604...,,0
7,13,13261848,Joshua (Josh),Noel,Hogan,1,CA,US,UNITED STATES,residence,matched (3),Joshua (Josh) Noel Hogan,Joshua (Josh) Hogan,California,,,0
8,15,13356632,Kai,,Tao,1,,CN,CHINA,residence,matched (3),Kai Tao,Kai Tao,,,,0
9,16,13391446,Eckhard,,Lohde,2,,DE,GERMANY,residence,matched (3),Eckhard Lohde,Eckhard Lohde,,https://www.linkedin.com/in/eckhard-l%C3%B6hde...,,0
10,17,13391446,Olaf,,Christiansen,1,,DE,GERMANY,postal,matched (3),Olaf Christiansen,Olaf Christiansen,,https://www.linkedin.com/in/olaf-christiansen-...,,0
11,19,13426684,David,,Hirshberg,1,,IL,ISRAEL,residence,matched (3),David Hirshberg,David Hirshberg,,https://www.linkedin.com/in/david-hirshberg-b6...,,0
12,21,13438140,Mark,Macdonough,Robinson,1,MA,US,UNITED STATES,residence,matched (3),Mark Macdonough Robinson,Mark Robinson,Massachusetts,,,0
13,23,13442888,Chaloke,,Pungtrakul,1,,TH,THAILAND,residence,matched (3),Chaloke Pungtrakul,Chaloke Pungtrakul,,None,,0
14,25,13465206,Steven,B.,Tracy,1,ME,US,UNITED STATES,postal,matched (3),Steven B. Tracy,Steven Tracy,Maine,,,0
15,27,13465375,Liu,,Yang,1,CA,US,UNITED STATES,postal,matched (3),Liu Yang,Liu Yang,California,https://www.linkedin.com/in/liu-yang-ph-d-0452...,,0
16,29,13465375,Fang,,Sheng,2,CA,US,UNITED STATES,residence,matched (3),Fang Sheng,Fang Sheng,California,,,0
17,30,13467009,David,J.,Mishelevich,1,CA,US,UNITED STATES,postal,matched (3),David J. Mishelevich,David Mishelevich,California,https://www.linkedin.com/in/david-mishelevich-...,,0
18,32,13474326,Norman,Scott,Peckenpaugh,1,WA,US,UNITED STATES,postal,matched (3),Norman Scott Peckenpaugh,Norman Peckenpaugh,Washington,None,,0
19,36,13481539,Laszlo,,Redey,1,IL,US,UNITED STATES,postal,matched (3),Laszlo Redey,Laszlo Redey,Illinois,https://www.linkedin.com/in/laszlo-redey-a5746...,,0
20,38,13482342,Michael,Robert,White,1,CA,US,UNITED STATES,postal,matched (3),Michael Robert White,Michael White,California,,,0
21,40,13484165,Sergey,,Anikin,1,CA,US,,postal,matched (3),Sergey Anikin,Sergey Anikin,California,,,0
22,42,13486438,Benjamin,,Pouladian,2,CA,US,UNITED STATES,residence,matched (3),Benjamin Pouladian,Benjamin Pouladian,California,https://www.linkedin.com/in/benpouladian/,,0
23,43,13486438,Saman,,Sinai,1,CA,US,UNITED STATES,residence,matched (3),Saman Sinai,Saman Sinai,California,https://www.linkedin.com/in/sam-jr-sinai-6970b...,,0
24,45,13487252,Yong-Kyu,,Jung,1,TX,US,UNITED STATES,residence,matched (3),Yong-Kyu Jung,Yong-Kyu Jung,Texas,https://www.linkedin.com/in/yong-kyu-jung-5794...,,0
25,47,13490478,Gabriel,,Yavor,1,,IL,ISRAEL,residence,matched (3),Gabriel Yavor,Gabriel Yavor,,https://www.linkedin.com/in/gabriel-yavor-5b4603/,,0
26,49,13494995,Shih-Lin,,Chang,3,,TW,TAIWAN,residence,matched (3),Shih-Lin Chang,Shih-Lin Chang,,,,0
27,50,13494995,Bin-Juine,,Huang,1,,TW,TAIWAN,residence,matched (3),Bin-Juine Huang,Bin-Juine Huang,,https://www.linkedin.com/in/jinfhuang/,,0
28,52,13494995,Jong-Fu,,Yeh,2,,TW,TAIWAN,residence,matched (3),Jong-Fu Yeh,Jong-Fu Yeh,,,,0
29,53,13500071,Arun,,Jain,1,NJ,US,UNITED STATES,postal,matched (3),Arun Jain,Arun Jain,New Jersey,,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705,3538,14508107,Kellsie,,Shan,2,NY,US,UNITED STATES,residence,matched (3),Kellsie Shan,Kellsie Shan,New York,None,,0
1706,3541,14515804,Lucas,,Mclelan,1,CA,US,,postal,matched (3),Lucas Mclelan,Lucas Mclelan,California,https://www.linkedin.com/in/lucas-mclelan-2785...,,0
1707,3545,14523946,Xiwang,,Qi,1,AZ,US,UNITED STATES,residence,matched (3),Xiwang Qi,Xiwang Qi,Arizona,https://www.linkedin.com/in/xiwang-michael-qi-...,,0
1708,3546,14523946,Mei,,Jiang,2,AZ,US,UNITED STATES,residence,matched (3),Mei Jiang,Mei Jiang,Arizona,,,0
1709,3549,14533137,Yu-Cheng,,Huang,1,,TW,TAIWAN,residence,matched (3),Yu-Cheng Huang,Yu-Cheng Huang,,,,0
1710,3551,14537987,Gioulchen,,Tairova,1,ON,CA,CANADA,postal,matched (3),Gioulchen Tairova,Gioulchen Tairova,,None,,0
1711,3552,14537987,Junian,,Ioffe,2,,CA,CANADA,residence,matched (3),Junian Ioffe,Junian Ioffe,,https://www.linkedin.com/in/junianioffe/,,0
1712,3554,14550910,George,,Pul,1,NV,US,,postal,matched (3),George Pul,George Pul,Nevada,None,,0
1713,3556,14555666,Rejean,,Plante,1,,CA,CANADA,residence,matched (3),Rejean Plante,Rejean Plante,,https://www.linkedin.com/in/r%C3%A9jean-plante...,,0
1714,3558,14555666,Louise,,Cusson,2,,CA,CANADA,residence,matched (3),Louise Cusson,Louise Cusson,,None,,0
1715,3559,14559908,Craig,,Brodersen,1,OR,US,,postal,matched (3),Craig Brodersen,Craig Brodersen,Oregon,https://www.linkedin.com/in/craig-brodersen-52...,,0
1716,3561,14572956,Robert,,Creighton,2,PA,US,UNITED STATES,residence,matched (3),Robert Creighton,Robert Creighton,Pennsylvania,https://www.linkedin.com/in/bob-creighton/,,0
1717,3562,14572956,Arup,,Sengupta,1,PA,US,UNITED STATES,residence,matched (3),Arup Sengupta,Arup Sengupta,Pennsylvania,https://www.linkedin.com/in/arup-sengupta-b963...,,0
1718,3565,14658217,Sergey,Petrovich,Tsyukalo,1,WA,US,,postal,matched (3),Sergey Petrovich Tsyukalo,Sergey Tsyukalo,Washington,https://www.linkedin.com/in/sergey-tsyukalo-38...,,0
1719,3567,13869501,David,John,Carr,,CT,US,UNITED STATES,,using only (2),David John Carr,David Carr,Connecticut,https://www.linkedin.com/in/david-carr-m-a-233...,,0
1720,3569,13998996,Charles,F.,Stewart,,CA,US,UNITED STATES,,using only (2),Charles F. Stewart,Charles Stewart,California,https://www.linkedin.com/in/dr-charles-stewart...,,0
1721,3570,14082148,Richard,Martin,Greene,,CA,US,UNITED STATES,,using only (2),Richard Martin Greene,Richard Greene,California,https://www.linkedin.com/in/rgreene/,,0
1722,3571,14083988,Christopher,Ralph,Tridico,,BC,US,UNITED STATES,,using only (2),Christopher Ralph Tridico,Christopher Tridico,,https://www.linkedin.com/in/christopher-tridic...,,0
1723,3572,14098711,Wei,,Song,,,,,,,Wei Song,Wei Song,,,,0
1724,3573,14098711,Xiao Wei,,Yu,,,,,,,Xiao Wei Yu,Xiao Wei Yu,,,,0
1725,3574,14098711,Weiping,,Ren,,,,,,using only (2),Weiping Ren,Weiping Ren,,,,0
1726,3575,14201795,David,,Galomb,,PA,US,UNITED STATES,,using only (2),David Galomb,David Galomb,Pennsylvania,https://www.linkedin.com/in/dave-g-246181167/,,1
1727,3576,14214687,William,S.,Baron,,,,,,using only (2),William S. Baron,William Baron,,,,0
1728,3577,14214687,Sandra,F.,Baron,,,,,,,Sandra F. Baron,Sandra Baron,,https://www.linkedin.com/in/baronsandra/,,0
1729,3578,14250378,Matthew,Carl,O'Malley,,,,,,using only (2),Matthew Carl O'Malley,Matthew O'Malley,,,,0
1730,3579,14257778,Nabyl,,Bennouri,,,,,,,Nabyl Bennouri,Nabyl Bennouri,,https://www.linkedin.com/in/nabyl-bennouri-707...,,0
1731,3580,14257778,Jie,,Lian,,,,,,,Jie Lian,Jie Lian,,https://www.linkedin.com/in/jie-lian-20bb9331,,0
1732,3581,14257778,Nattapon,,Chaimanoart,,,,,,using only (2),Nattapon Chaimanoart,Nattapon Chaimanoart,,,,0
1733,3582,14280605,Oliver,Markus,Haynold,,,,,,using only (2),Oliver Markus Haynold,Oliver Haynold,,https://www.linkedin.com/in/olivermhaynold/,,0
1734,3583,14451811,Randall,C.,Wilson,,,,,,using only (2),Randall C. Wilson,Randall Wilson,,https://www.linkedin.com/in/randall-wilson-475...,,0

In [73]:
dupes = fix.duplicated(subset = ['inventor_name_last','inventor_name_first','inventor_region_code'],keep=False)
print(dupes)

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
1705    False
1706     True
1707    False
1708    False
1709    False
1710    False
1711    False
1712    False
1713    False
1714    False
1715    False
1716    False
1717    False
1718    False
1719    False
1720    False
1721    False
1722    False
1723    False
1724    False
1725    False
1726     True
1727    False
1728    False
1729    False
1730    False
1731    False
1732    False
1733    False
1734    False
Length: 1735, dtype: bool

In [75]:
new = pd.concat([fix, dupes], axis=1)

In [76]:
new

,Original Index,appl_id,inventor_name_first,inventor_name_middle,inventor_name_last,inventor_rank,inventor_region_code,inventor_country_code,inventor_country_name,inventor_address_type,_merge,full_name,first_last_name,state,linkedinProfile,Maybe,Duplicates,0
0,0,13199870,Durand,Kevin,Dickerson,1,KS,US,UNITED STATES,residence,matched (3),Durand Kevin Dickerson,Durand Dickerson,Kansas,https://www.linkedin.com/in/durand-dickerson-b...,,0,False
1,2,13199870,Lawrence,Derwood,Kenemore,2,KS,US,UNITED STATES,residence,matched (3),Lawrence Derwood Kenemore,Lawrence Kenemore,Kansas,https://www.linkedin.com/in/larry-kenemore-jr-...,,0,False
2,3,13261475,Stefanos,,Ntoukolianos,1,,GR,GREECE,postal,matched (3),Stefanos Ntoukolianos,Stefanos Ntoukolianos,,None,,0,False
3,5,13261723,Mukul,Chandra,Gope,1,,IN,INDIA,postal,matched (3),Mukul Chandra Gope,Mukul Gope,,None,,0,False
4,7,13261789,Mitsutoshi,,Sugawara,1,,JP,JAPAN,postal,matched (3),Mitsutoshi Sugawara,Mitsutoshi Sugawara,,https://www.linkedin.com/in/mitsutoshi-sugawar...,,0,False
5,9,13261809,Georgios,,Mavroeidis,1,,GR,GREECE,residence,matched (3),Georgios Mavroeidis,Georgios Mavroeidis,,https://www.linkedin.com/in/georgios-mavroeidi...,,0,False
6,11,13261831,Lorena,,Dordan,1,CA,US,UNITED STATES,residence,matched (3),Lorena Dordan,Lorena Dordan,California,https://www.linkedin.com/in/lorena-dordan-a604...,,0,False
7,13,13261848,Joshua (Josh),Noel,Hogan,1,CA,US,UNITED STATES,residence,matched (3),Joshua (Josh) Noel Hogan,Joshua (Josh) Hogan,California,,,0,False
8,15,13356632,Kai,,Tao,1,,CN,CHINA,residence,matched (3),Kai Tao,Kai Tao,,,,0,False
9,16,13391446,Eckhard,,Lohde,2,,DE,GERMANY,residence,matched (3),Eckhard Lohde,Eckhard Lohde,,https://www.linkedin.com/in/eckhard-l%C3%B6hde...,,0,False
10,17,13391446,Olaf,,Christiansen,1,,DE,GERMANY,postal,matched (3),Olaf Christiansen,Olaf Christiansen,,https://www.linkedin.com/in/olaf-christiansen-...,,0,False
11,19,13426684,David,,Hirshberg,1,,IL,ISRAEL,residence,matched (3),David Hirshberg,David Hirshberg,,https://www.linkedin.com/in/david-hirshberg-b6...,,0,False
12,21,13438140,Mark,Macdonough,Robinson,1,MA,US,UNITED STATES,residence,matched (3),Mark Macdonough Robinson,Mark Robinson,Massachusetts,,,0,False
13,23,13442888,Chaloke,,Pungtrakul,1,,TH,THAILAND,residence,matched (3),Chaloke Pungtrakul,Chaloke Pungtrakul,,None,,0,False
14,25,13465206,Steven,B.,Tracy,1,ME,US,UNITED STATES,postal,matched (3),Steven B. Tracy,Steven Tracy,Maine,,,0,False
15,27,13465375,Liu,,Yang,1,CA,US,UNITED STATES,postal,matched (3),Liu Yang,Liu Yang,California,https://www.linkedin.com/in/liu-yang-ph-d-0452...,,0,False
16,29,13465375,Fang,,Sheng,2,CA,US,UNITED STATES,residence,matched (3),Fang Sheng,Fang Sheng,California,,,0,False
17,30,13467009,David,J.,Mishelevich,1,CA,US,UNITED STATES,postal,matched (3),David J. Mishelevich,David Mishelevich,California,https://www.linkedin.com/in/david-mishelevich-...,,0,False
18,32,13474326,Norman,Scott,Peckenpaugh,1,WA,US,UNITED STATES,postal,matched (3),Norman Scott Peckenpaugh,Norman Peckenpaugh,Washington,None,,0,False
19,36,13481539,Laszlo,,Redey,1,IL,US,UNITED STATES,postal,matched (3),Laszlo Redey,Laszlo Redey,Illinois,https://www.linkedin.com/in/laszlo-redey-a5746...,,0,False
20,38,13482342,Michael,Robert,White,1,CA,US,UNITED STATES,postal,matched (3),Michael Robert White,Michael White,California,,,0,False
21,40,13484165,Sergey,,Anikin,1,CA,US,,postal,matched (3),Sergey Anikin,Sergey Anikin,California,,,0,False
22,42,13486438,Benjamin,,Pouladian,2,CA,US,UNITED STATES,residence,matched (3),Benjamin Pouladian,Benjamin Pouladian,California,https://www.linkedin.com/in/benpouladian/,,0,False
23,43,13486438,Saman,,Sinai,1,CA,US,UNITED STATES,residence,matched (3),Saman Sinai,Saman Sinai,California,https://www.linkedin.com/in/sam-jr-sinai-6970b...,,0,False
24,45,13487252,Yong-Kyu,,Jung,1,TX,US,UNITED STATES,residence,matched (3),Yong-Kyu Jung,Yong-Kyu Jung,Texas,https://www.linkedin.com/in/yong-kyu-jung-5794...,,0,False
25,47,13490478,Gabriel,,Yavor,1,,IL,ISRAEL,residence,matched (3),Gabriel Yavor,Gabriel Yavor,,https://www.linkedin.com/in/gabriel-yavor-5b4603/,,0,False
26,49,13494995,Shih-Lin,,Chang,3,,TW,TAIWAN,residence,matched (3),Shih-Lin Chang,Shih-Lin Chang,,,,0,False
27,50,13494995,Bin-Juine,,Huang,1,,TW,TAIWAN,residence,matched (3),Bin-Juine Huang,Bin-Juine Huang,,https://www.linkedin.com/in/jinfhuang/,,0,False
28,52,13494995,Jong-Fu,,Yeh,2,,TW,TAIWAN,residence,matched (3),Jong-Fu Yeh,Jong-Fu Yeh,,,,0,False
29,53,13500071,Arun,,Jain,1,NJ,US,UNITED STATES,postal,matched (3),Arun Jain,Arun Jain,New Jersey,,,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705,3538,14508107,Kellsie,,Shan,2,NY,US,UNITED STATES,residence,matched (3),Kellsie Shan,Kellsie Shan,New York,None,,0,False
1706,3541,14515804,Lucas,,Mclelan,1,CA,US,,postal,matched (3),Lucas Mclelan,Lucas Mclelan,California,https://www.linkedin.com/in/lucas-mclelan-2785...,,0,False
1707,3545,14523946,Xiwang,,Qi,1,AZ,US,UNITED STATES,residence,matched (3),Xiwang Qi,Xiwang Qi,Arizona,https://www.linkedin.com/in/xiwang-michael-qi-...,,0,False
1708,3546,14523946,Mei,,Jiang,2,AZ,US,UNITED STATES,residence,matched (3),Mei Jiang,Mei Jiang,Arizona,,,0,False
1709,3549,14533137,Yu-Cheng,,Huang,1,,TW,TAIWAN,residence,matched (3),Yu-Cheng Huang,Yu-Cheng Huang,,,,0,False
1710,3551,14537987,Gioulchen,,Tairova,1,ON,CA,CANADA,postal,matched (3),Gioulchen Tairova,Gioulchen Tairova,,None,,0,False
1711,3552,14537987,Junian,,Ioffe,2,,CA,CANADA,residence,matched (3),Junian Ioffe,Junian Ioffe,,https://www.linkedin.com/in/junianioffe/,,0,False
1712,3554,14550910,George,,Pul,1,NV,US,,postal,matched (3),George Pul,George Pul,Nevada,None,,0,False
1713,3556,14555666,Rejean,,Plante,1,,CA,CANADA,residence,matched (3),Rejean Plante,Rejean Plante,,https://www.linkedin.com/in/r%C3%A9jean-plante...,,0,False
1714,3558,14555666,Louise,,Cusson,2,,CA,CANADA,residence,matched (3),Louise Cusson,Louise Cusson,,None,,0,False
1715,3559,14559908,Craig,,Brodersen,1,OR,US,,postal,matched (3),Craig Brodersen,Craig Brodersen,Oregon,https://www.linkedin.com/in/craig-brodersen-52...,,0,False
1716,3561,14572956,Robert,,Creighton,2,PA,US,UNITED STATES,residence,matched (3),Robert Creighton,Robert Creighton,Pennsylvania,https://www.linkedin.com/in/bob-creighton/,,0,False
1717,3562,14572956,Arup,,Sengupta,1,PA,US,UNITED STATES,residence,matched (3),Arup Sengupta,Arup Sengupta,Pennsylvania,https://www.linkedin.com/in/arup-sengupta-b963...,,0,False
1718,3565,14658217,Sergey,Petrovich,Tsyukalo,1,WA,US,,postal,matched (3),Sergey Petrovich Tsyukalo,Sergey Tsyukalo,Washington,https://www.linkedin.com/in/sergey-tsyukalo-38...,,0,False
1719,3567,13869501,David,John,Carr,,CT,US,UNITED STATES,,using only (2),David John Carr,David Carr,Connecticut,https://www.linkedin.com/in/david-carr-m-a-233...,,0,False
1720,3569,13998996,Charles,F.,Stewart,,CA,US,UNITED STATES,,using only (2),Charles F. Stewart,Charles Stewart,California,https://www.linkedin.com/in/dr-charles-stewart...,,0,False
1721,3570,14082148,Richard,Martin,Greene,,CA,US,UNITED STATES,,using only (2),Richard Martin Greene,Richard Greene,California,https://www.linkedin.com/in/rgreene/,,0,False
1722,3571,14083988,Christopher,Ralph,Tridico,,BC,US,UNITED STATES,,using only (2),Christopher Ralph Tridico,Christopher Tridico,,https://www.linkedin.com/in/christopher-tridic...,,0,False
1723,3572,14098711,Wei,,Song,,,,,,,Wei Song,Wei Song,,,,0,False
1724,3573,14098711,Xiao Wei,,Yu,,,,,,,Xiao Wei Yu,Xiao Wei Yu,,,,0,False
1725,3574,14098711,Weiping,,Ren,,,,,,using only (2),Weiping Ren,Weiping Ren,,,,0,False
1726,3575,14201795,David,,Galomb,,PA,US,UNITED STATES,,using only (2),David Galomb,David Galomb,Pennsylvania,https://www.linkedin.com/in/dave-g-246181167/,,1,True
1727,3576,14214687,William,S.,Baron,,,,,,using only (2),William S. Baron,William Baron,,,,0,False
1728,3577,14214687,Sandra,F.,Baron,,,,,,,Sandra F. Baron,Sandra Baron,,https://www.linkedin.com/in/baronsandra/,,0,False
1729,3578,14250378,Matthew,Carl,O'Malley,,,,,,using only (2),Matthew Carl O'Malley,Matthew O'Malley,,,,0,False
1730,3579,14257778,Nabyl,,Bennouri,,,,,,,Nabyl Bennouri,Nabyl Bennouri,,https://www.linkedin.com/in/nabyl-bennouri-707...,,0,False
1731,3580,14257778,Jie,,Lian,,,,,,,Jie Lian,Jie Lian,,https://www.linkedin.com/in/jie-lian-20bb9331,,0,False
1732,3581,14257778,Nattapon,,Chaimanoart,,,,,,using only (2),Nattapon Chaimanoart,Nattapon Chaimanoart,,,,0,False
1733,3582,14280605,Oliver,Markus,Haynold,,,,,,using only (2),Oliver Markus Haynold,Oliver Haynold,,https://www.linkedin.com/in/olivermhaynold/,,0,False
1734,3583,14451811,Randall,C.,Wilson,,,,,,using only (2),Randall C. Wilson,Randall Wilson,,https://www.linkedin.com/in/randall-wilson-475...,,0,False

In [86]:
new = new.rename({0:'Dupe'}, axis = 1)
new.Dupe = new.Dupe.astype(int)

new

,Original Index,appl_id,inventor_name_first,inventor_name_middle,inventor_name_last,inventor_rank,inventor_region_code,inventor_country_code,inventor_country_name,inventor_address_type,_merge,full_name,first_last_name,state,linkedinProfile,Maybe,Duplicates,Dupe
0,0,13199870,Durand,Kevin,Dickerson,1,KS,US,UNITED STATES,residence,matched (3),Durand Kevin Dickerson,Durand Dickerson,Kansas,https://www.linkedin.com/in/durand-dickerson-b...,,0,0
1,2,13199870,Lawrence,Derwood,Kenemore,2,KS,US,UNITED STATES,residence,matched (3),Lawrence Derwood Kenemore,Lawrence Kenemore,Kansas,https://www.linkedin.com/in/larry-kenemore-jr-...,,0,0
2,3,13261475,Stefanos,,Ntoukolianos,1,,GR,GREECE,postal,matched (3),Stefanos Ntoukolianos,Stefanos Ntoukolianos,,None,,0,0
3,5,13261723,Mukul,Chandra,Gope,1,,IN,INDIA,postal,matched (3),Mukul Chandra Gope,Mukul Gope,,None,,0,0
4,7,13261789,Mitsutoshi,,Sugawara,1,,JP,JAPAN,postal,matched (3),Mitsutoshi Sugawara,Mitsutoshi Sugawara,,https://www.linkedin.com/in/mitsutoshi-sugawar...,,0,0
5,9,13261809,Georgios,,Mavroeidis,1,,GR,GREECE,residence,matched (3),Georgios Mavroeidis,Georgios Mavroeidis,,https://www.linkedin.com/in/georgios-mavroeidi...,,0,0
6,11,13261831,Lorena,,Dordan,1,CA,US,UNITED STATES,residence,matched (3),Lorena Dordan,Lorena Dordan,California,https://www.linkedin.com/in/lorena-dordan-a604...,,0,0
7,13,13261848,Joshua (Josh),Noel,Hogan,1,CA,US,UNITED STATES,residence,matched (3),Joshua (Josh) Noel Hogan,Joshua (Josh) Hogan,California,,,0,0
8,15,13356632,Kai,,Tao,1,,CN,CHINA,residence,matched (3),Kai Tao,Kai Tao,,,,0,0
9,16,13391446,Eckhard,,Lohde,2,,DE,GERMANY,residence,matched (3),Eckhard Lohde,Eckhard Lohde,,https://www.linkedin.com/in/eckhard-l%C3%B6hde...,,0,0
10,17,13391446,Olaf,,Christiansen,1,,DE,GERMANY,postal,matched (3),Olaf Christiansen,Olaf Christiansen,,https://www.linkedin.com/in/olaf-christiansen-...,,0,0
11,19,13426684,David,,Hirshberg,1,,IL,ISRAEL,residence,matched (3),David Hirshberg,David Hirshberg,,https://www.linkedin.com/in/david-hirshberg-b6...,,0,0
12,21,13438140,Mark,Macdonough,Robinson,1,MA,US,UNITED STATES,residence,matched (3),Mark Macdonough Robinson,Mark Robinson,Massachusetts,,,0,0
13,23,13442888,Chaloke,,Pungtrakul,1,,TH,THAILAND,residence,matched (3),Chaloke Pungtrakul,Chaloke Pungtrakul,,None,,0,0
14,25,13465206,Steven,B.,Tracy,1,ME,US,UNITED STATES,postal,matched (3),Steven B. Tracy,Steven Tracy,Maine,,,0,0
15,27,13465375,Liu,,Yang,1,CA,US,UNITED STATES,postal,matched (3),Liu Yang,Liu Yang,California,https://www.linkedin.com/in/liu-yang-ph-d-0452...,,0,0
16,29,13465375,Fang,,Sheng,2,CA,US,UNITED STATES,residence,matched (3),Fang Sheng,Fang Sheng,California,,,0,0
17,30,13467009,David,J.,Mishelevich,1,CA,US,UNITED STATES,postal,matched (3),David J. Mishelevich,David Mishelevich,California,https://www.linkedin.com/in/david-mishelevich-...,,0,0
18,32,13474326,Norman,Scott,Peckenpaugh,1,WA,US,UNITED STATES,postal,matched (3),Norman Scott Peckenpaugh,Norman Peckenpaugh,Washington,None,,0,0
19,36,13481539,Laszlo,,Redey,1,IL,US,UNITED STATES,postal,matched (3),Laszlo Redey,Laszlo Redey,Illinois,https://www.linkedin.com/in/laszlo-redey-a5746...,,0,0
20,38,13482342,Michael,Robert,White,1,CA,US,UNITED STATES,postal,matched (3),Michael Robert White,Michael White,California,,,0,0
21,40,13484165,Sergey,,Anikin,1,CA,US,,postal,matched (3),Sergey Anikin,Sergey Anikin,California,,,0,0
22,42,13486438,Benjamin,,Pouladian,2,CA,US,UNITED STATES,residence,matched (3),Benjamin Pouladian,Benjamin Pouladian,California,https://www.linkedin.com/in/benpouladian/,,0,0
23,43,13486438,Saman,,Sinai,1,CA,US,UNITED STATES,residence,matched (3),Saman Sinai,Saman Sinai,California,https://www.linkedin.com/in/sam-jr-sinai-6970b...,,0,0
24,45,13487252,Yong-Kyu,,Jung,1,TX,US,UNITED STATES,residence,matched (3),Yong-Kyu Jung,Yong-Kyu Jung,Texas,https://www.linkedin.com/in/yong-kyu-jung-5794...,,0,0
25,47,13490478,Gabriel,,Yavor,1,,IL,ISRAEL,residence,matched (3),Gabriel Yavor,Gabriel Yavor,,https://www.linkedin.com/in/gabriel-yavor-5b4603/,,0,0
26,49,13494995,Shih-Lin,,Chang,3,,TW,TAIWAN,residence,matched (3),Shih-Lin Chang,Shih-Lin Chang,,,,0,0
27,50,13494995,Bin-Juine,,Huang,1,,TW,TAIWAN,residence,matched (3),Bin-Juine Huang,Bin-Juine Huang,,https://www.linkedin.com/in/jinfhuang/,,0,0
28,52,13494995,Jong-Fu,,Yeh,2,,TW,TAIWAN,residence,matched (3),Jong-Fu Yeh,Jong-Fu Yeh,,,,0,0
29,53,13500071,Arun,,Jain,1,NJ,US,UNITED STATES,postal,matched (3),Arun Jain,Arun Jain,New Jersey,,,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705,3538,14508107,Kellsie,,Shan,2,NY,US,UNITED STATES,residence,matched (3),Kellsie Shan,Kellsie Shan,New York,None,,0,0
1706,3541,14515804,Lucas,,Mclelan,1,CA,US,,postal,matched (3),Lucas Mclelan,Lucas Mclelan,California,https://www.linkedin.com/in/lucas-mclelan-2785...,,0,0
1707,3545,14523946,Xiwang,,Qi,1,AZ,US,UNITED STATES,residence,matched (3),Xiwang Qi,Xiwang Qi,Arizona,https://www.linkedin.com/in/xiwang-michael-qi-...,,0,0
1708,3546,14523946,Mei,,Jiang,2,AZ,US,UNITED STATES,residence,matched (3),Mei Jiang,Mei Jiang,Arizona,,,0,0
1709,3549,14533137,Yu-Cheng,,Huang,1,,TW,TAIWAN,residence,matched (3),Yu-Cheng Huang,Yu-Cheng Huang,,,,0,0
1710,3551,14537987,Gioulchen,,Tairova,1,ON,CA,CANADA,postal,matched (3),Gioulchen Tairova,Gioulchen Tairova,,None,,0,0
1711,3552,14537987,Junian,,Ioffe,2,,CA,CANADA,residence,matched (3),Junian Ioffe,Junian Ioffe,,https://www.linkedin.com/in/junianioffe/,,0,0
1712,3554,14550910,George,,Pul,1,NV,US,,postal,matched (3),George Pul,George Pul,Nevada,None,,0,0
1713,3556,14555666,Rejean,,Plante,1,,CA,CANADA,residence,matched (3),Rejean Plante,Rejean Plante,,https://www.linkedin.com/in/r%C3%A9jean-plante...,,0,0
1714,3558,14555666,Louise,,Cusson,2,,CA,CANADA,residence,matched (3),Louise Cusson,Louise Cusson,,None,,0,0
1715,3559,14559908,Craig,,Brodersen,1,OR,US,,postal,matched (3),Craig Brodersen,Craig Brodersen,Oregon,https://www.linkedin.com/in/craig-brodersen-52...,,0,0
1716,3561,14572956,Robert,,Creighton,2,PA,US,UNITED STATES,residence,matched (3),Robert Creighton,Robert Creighton,Pennsylvania,https://www.linkedin.com/in/bob-creighton/,,0,0
1717,3562,14572956,Arup,,Sengupta,1,PA,US,UNITED STATES,residence,matched (3),Arup Sengupta,Arup Sengupta,Pennsylvania,https://www.linkedin.com/in/arup-sengupta-b963...,,0,0
1718,3565,14658217,Sergey,Petrovich,Tsyukalo,1,WA,US,,postal,matched (3),Sergey Petrovich Tsyukalo,Sergey Tsyukalo,Washington,https://www.linkedin.com/in/sergey-tsyukalo-38...,,0,0
1719,3567,13869501,David,John,Carr,,CT,US,UNITED STATES,,using only (2),David John Carr,David Carr,Connecticut,https://www.linkedin.com/in/david-carr-m-a-233...,,0,0
1720,3569,13998996,Charles,F.,Stewart,,CA,US,UNITED STATES,,using only (2),Charles F. Stewart,Charles Stewart,California,https://www.linkedin.com/in/dr-charles-stewart...,,0,0
1721,3570,14082148,Richard,Martin,Greene,,CA,US,UNITED STATES,,using only (2),Richard Martin Greene,Richard Greene,California,https://www.linkedin.com/in/rgreene/,,0,0
1722,3571,14083988,Christopher,Ralph,Tridico,,BC,US,UNITED STATES,,using only (2),Christopher Ralph Tridico,Christopher Tridico,,https://www.linkedin.com/in/christopher-tridic...,,0,0
1723,3572,14098711,Wei,,Song,,,,,,,Wei Song,Wei Song,,,,0,0
1724,3573,14098711,Xiao Wei,,Yu,,,,,,,Xiao Wei Yu,Xiao Wei Yu,,,,0,0
1725,3574,14098711,Weiping,,Ren,,,,,,using only (2),Weiping Ren,Weiping Ren,,,,0,0
1726,3575,14201795,David,,Galomb,,PA,US,UNITED STATES,,using only (2),David Galomb,David Galomb,Pennsylvania,https://www.linkedin.com/in/dave-g-246181167/,,1,1
1727,3576,14214687,William,S.,Baron,,,,,,using only (2),William S. Baron,William Baron,,,,0,0
1728,3577,14214687,Sandra,F.,Baron,,,,,,,Sandra F. Baron,Sandra Baron,,https://www.linkedin.com/in/baronsandra/,,0,0
1729,3578,14250378,Matthew,Carl,O'Malley,,,,,,using only (2),Matthew Carl O'Malley,Matthew O'Malley,,,,0,0
1730,3579,14257778,Nabyl,,Bennouri,,,,,,,Nabyl Bennouri,Nabyl Bennouri,,https://www.linkedin.com/in/nabyl-bennouri-707...,,0,0
1731,3580,14257778,Jie,,Lian,,,,,,,Jie Lian,Jie Lian,,https://www.linkedin.com/in/jie-lian-20bb9331,,0,0
1732,3581,14257778,Nattapon,,Chaimanoart,,,,,,using only (2),Nattapon Chaimanoart,Nattapon Chaimanoart,,,,0,0
1733,3582,14280605,Oliver,Markus,Haynold,,,,,,using only (2),Oliver Markus Haynold,Oliver Haynold,,https://www.linkedin.com/in/olivermhaynold/,,0,0
1734,3583,14451811,Randall,C.,Wilson,,,,,,using only (2),Randall C. Wilson,Randall Wilson,,https://www.linkedin.com/in/randall-wilson-475...,,0,0

In [83]:
mismatch = new['Duplicates'] != new['Dupe']

In [85]:
mismatch

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
1705    False
1706    False
1707    False
1708    False
1709    False
1710    False
1711    False
1712    False
1713    False
1714    False
1715    False
1716    False
1717    False
1718    False
1719    False
1720    False
1721    False
1722    False
1723    False
1724    False
1725    False
1726    False
1727    False
1728    False
1729    False
1730    False
1731    False
1732    False
1733    False
1734    False
Length: 1735, dtype: bool