In [ ]:
import pandas as pd
import numpy as np
import csv

In [61]:
# final with correct links
final = pd.read_csv("final.csv", encoding = "ISO-8859-1", delimiter = ',', dtype = object)
final = final.drop(['Unnamed: 0'], axis = 1)

In [62]:
# Phantombuster file (pt1)
result = pd.read_csv("phantombuster_pt1.csv", encoding = "ISO-8859-1", delimiter = ',', dtype = object)

In [74]:
# replace all commas with periods 
result = result.stack().str.replace(',','.').unstack()

# cast links as strings
final['linkedinProfile'] = final['linkedinProfile'].astype(str)
result['linkedinProfile'] = result['linkedinProfile'].astype(str)

In [64]:
# display column names of final
final.columns

Index(['original_index', 'appl_id', 'inventor_name_first',
       'inventor_name_middle', 'inventor_name_last', 'inventor_rank',
       'inventor_region_code', 'inventor_country_code',
       'inventor_country_name', 'inventor_address_type', '_merge', 'state',
       'linkedinProfile', 'Maybe', 'Duplicates', 'unique', 'full_name'],
      dtype='object')

In [65]:
# display column names of result
result.columns

Index(['linkedinProfile', 'firstName', 'lastName', 'fullName',
       'connectionDegree', 'vmid', 'company', 'companyUrl', 'jobTitle',
       'jobDescription', 'location', 'company2', 'companyUrl2', 'jobTitle2',
       'location2', 'school', 'schoolUrl', 'schoolDateRange', 'school2',
       'schoolUrl2', 'schoolDateRange2', 'baseUrl', 'profileId', 'timestamp',
       'description', 'imgUrl', 'jobDescription2', 'schoolDegree',
       'schoolDegreeSpec', 'schoolDegreeSpec2', 'allSkills', 'skill1',
       'endorsement1', 'skill2', 'endorsement2', 'skill3', 'endorsement3',
       'skill4', 'endorsement4', 'skill5', 'endorsement5', 'skill6',
       'endorsement6', 'schoolDescription', 'schoolDegree2',
       'schoolDescription2', 'twitter', 'mail'],
      dtype='object')

In [70]:
result

,linkedinProfile,firstName,lastName,fullName,connectionDegree,vmid,company,companyUrl,jobTitle,jobDescription,...,endorsement4,skill5,endorsement5,skill6,endorsement6,schoolDescription,schoolDegree2,schoolDescription2,twitter,mail
0,https://www.linkedin.com/in/durand-dickerson-b...,Durand,Dickerson,Durand Dickerson,åÊ,ACoAABP_NxoBehFb8wNw6Xb68zAdu98HNSI2AtM,Fill-A-Box Corporation,https://www.linkedin.com/search/results/index/...,President,Currently serve as the President. Secretary. T...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.linkedin.com/in/mitsutoshi-sugawar...,Mitsutoshi,Sugawara,Mitsutoshi Sugawara,åÊ,ACoAABIGLZAB9JUUsgMuM83SbQpi9Uk6bqh-L4M,¾±¼Âá´¾´__¤__,https://www.linkedin.com/search/results/index/...,Researcher,Designing novel ADC.DAC.PLL.RF_amp architectur...,...,1,IC,0,LSI¬_¬ö,1,NaN,NaN,NaN,NaN,NaN
2,https://www.linkedin.com/in/lorena-dordan-a604...,Lorena,Dordan,Lorena Dordan,3rd,ACoAAAU41ugBDLYwXAI4I3mMl1k9KeKIHHOryAI,HUMPSOL E.I.R.L.,https://www.linkedin.com/company/7949997/,Product Developer. IP protection. Packaging. S...,Û¢\tImagination. Practicality. manufacturabil...,...,1,Patents,0,Product Design,0,Master Degree: International Relations.As of 2...,Bachelor's Degree,Bilingual in English and SpanishConcentration ...,NaN,NaN
3,https://www.linkedin.com/in/eckhard-l%C3%B6hde...,Eckhard,LÌ¦hde,Eckhard LÌ¦hde,åÊ,ACoAABA30YoBf737kQA6GtVBJM9HtsOZ2_Ez-KA,NaN,https://www.linkedin.com/search/results/index/,Chriruugische Praxis,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.linkedin.com/in/olaf-christiansen-...,Olaf,Christiansen,Olaf Christiansen,3rd,ACoAAAFE9z0BYYHSmQPxWAQ0tVDlA70eTf_HIQk,Home Shopping Europe,https://www.linkedin.com/company/38895/,Executive Vice President Human Resources,NaN,...,7,HR Consulting,4,Recruiting,4,NaN,NaN,NaN,NaN,NaN
5,https://www.linkedin.com/in/liu-yang-ph-d-0452...,Liu,Yang. Ph.D.,Liu Yang. Ph.D.,3rd,ACoAAA3qmnUBlThS9kRehVhqlDrziIGO3aSUCOw,Amazon,https://www.linkedin.com/company/1586/,Data Scientist III,Alexa Shopping NLU Data Science,...,30,R&D,13,Physics,46,Ranked 1st in the qualify exam in Physics. UC ...,Bachelor of Science (BS),NaN,NaN,NaN
6,https://www.linkedin.com/in/benpouladian/,Ben,Pouladian,Ben Pouladian,3rd,ACoAAABUmdcBIQ8aS5FeHrf5EU6UIu2prf1ybF0,Deco Lighting,https://www.linkedin.com/company/1322278/,Co-Founder. President,Deco Lightingå¨ is a leading provider of innov...,...,77,Business Development,52,Start-ups,47,Participated in cutting edge nano-scale optica...,NaN,NaN,getDECO,NaN
7,https://www.linkedin.com/in/sam-jr-sinai-6970b...,Sam,&#39;JR&#39; Sinai,Sam &#39;JR&#39; Sinai,3rd,ACoAAAPAi5MB0rGQSz94aKy4CPF0-cmHk-qWdlk,Deco Lighting,https://www.linkedin.com/company/1322278/,CEO And Co-Founder,DECO Lighting. America's leading manufacturer ...,...,59,Manufacturing,54,Competitive Analysis,44,NaN,Bacholor's Degree,NaN,NaN,NaN
8,https://www.linkedin.com/in/yong-kyu-jung-5794...,Yong,Kyu Jung,Yong Kyu Jung,åÊ,ACoAAB5Udq0BhL_B654n8HVj_s7sWEzWb4DBTz8,adaptmicrosys.com,https://www.linkedin.com/search/results/index/...,CTO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://www.linkedin.com/in/gabriel-yavor-5b4603/,Gabriel,Yavor,Gabriel Yavor,åÊ,ACoAAAAW35gBx3XMgRQIpSs-xThZOczoWdnvIxk,Optical Pulse Machines,https://www.linkedin.com/company/1130027/,Owner,OPM designs and manufactures high-speed electr...,...,19,R&D,15,Optical Fiber,13,NaN,MsC,NaN,NaN,NaN
10,https://www.linkedin.com/in/jinfhuang/,Jin,Huang,Jin Huang,3rd,ACoAAAIRi-ABIhbvsxH5DoyGvqeFCGDNnIcf2VQ,Workday,https://www.linkedin.com/company/17719/,Senior Software Engineer,ÛÒ A platform and data engineer leading the d...,...,7,Financial Modeling,6,Sales,2,I was enrolled in the PhD program. completed m...,Bachelor's degree,NaN,NaN,NaN
11,https://www.linkedin.com/in/antony-euclid-vill...,Antony-Euclid,Villa-Real,Antony-Euclid Villa-Real,åÊ,ACoAAA2q6m0BKgZTZEW-WEeOBxQIWxRDJoMCuvQ,EucliStar Global Technologies,https://www.linkedin.com/search/results/index/...,Founder-Inventor/CEO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,https://www.linkedin.com/in/sanza-kazadi-9733015/,Sanza,Kazadi,Sanza Kazadi,3rd,ACoAAADvQCcBWtEzmJ2xt53siK-ljxGdgKZQmbk,Energetically,https://www.linkedin.com/company/11804202/,Chief Technology Officer,Leading technology development for new energy ...,...,12,Robotics,10,Product Development,10,Computation and Neural Systems. ...,Bachelor's of Science,NaN,NaN,NaN
13,https://www.linkedin.com/in/james-glazier-92b9...,James,Glazier,James Glazier,åÊ,ACoAAAQPkrMBu2mOmoy0uNGR-vQqkAcjuYJ4RoU,Oxbo International,https://www.linkedin.com/search/results/index/...,Manager of Engineering,NaN,...,7,Engineering,7,Product Development,6,NaN,NaN,NaN,NaN,NaN
14,https://www.linkedin.com/in/tom-wehner-04623415/,Tom,Wehner,Tom Wehner,åÊ,ACoAAAMPNjYBhYgHFhx_qCRbPtBR9a3LsHrzlO0,SolarSPOT,https://www.linkedin.com/search/results/index/...,owner,NaN,...,NaN,NaN,NaN,NaN,NaN,Created the first Solar Energy Course at North...,NaN,NaN,NaN,NaN
15,https://www.linkedin.com/in/azita-mireshghi-17...,Azita,Mireshghi,Azita Mireshghi,åÊ,ACoAAB24pq0BTuiXcu28uNJ8OqG9Ix02J_BaR6E,Coordin8Care,https://www.linkedin.com/company/18498928/,Marketing Assistant,NaN,...,1,Sales,0,Modeling,0,NaN,Bachelor of Arts (BA),NaN,NaN,NaN
16,https://www.linkedin.com/in/roland-siemons-1a6...,Roland,Siemons,Roland Siemons,åÊ,ACoAAANDXo4BMDX5yQSX3CJsXopM2wMc2THbWTA,Clean Fuels,https://www.linkedin.com/search/results/index/...,Director,NaN,...,2,Climate Change,2,Energy,1,NaN,B.Sc,NaN,NaN,NaN
17,https://www.linkedin.com/in/jay-keeler-61609668/,jay,keeler,jay keeler,åÊ,ACoAAA5ABPIBaZK6sGP9pzVrc1p6DtMoVW0mzIE,confidential,https://www.linkedin.com/search/results/index/...,automation consultant,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,https://www.linkedin.com/in/venu-kandadai-9380...,Venu,Kandadai,Venu Kandadai,3rd,ACoAAALa3bwBeWxkOuRrk_zEA0JxHcAz7L5XL9A,Manjeera Digital Systems,https://www.linkedin.com/search/results/index/...,Founder & CEO,NaN,...,6,SoC,3,FPGA,3,NaN,Master of Philosophy (M.Phil.),NaN,NaN,NaN
19,https://www.linkedin.com/in/anna-khomenko-3509...,Anna,Khomenko,Anna Khomenko,åÊ,ACoAAATwjSwBqriOnosJf_bnskjeI7H-bw-e6M8,Panisolar,https://www.linkedin.com/search/results/index/...,Project manager,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,https://www.linkedin.com/in/tyler-back-43a1474/,Tyler,Back,Tyler Back,3rd,ACoAAAC7ga4B-ZXCG_Cs1RKS0SgFqx6Oaqxci4I,Synapse Product Development,https://www.linkedin.com/company/9389/,Mechanical Engineering Tech Lead,I'm part of a cross functional team of the sma...,...,7,Engineering,21,Manufacturing,13,NaN,Mechanical Engineer,six months Experienced culture overseas while ...,NaN,NaN
21,https://www.linkedin.com/in/alfred-haas-6703a212/,Alfred,Haas,Alfred Haas,åÊ,ACoAAAKMfzQBtODweaeI4qqGm_s4_AMq10vjYAw,BMW Manufacturing,https://www.linkedin.com/company/27825/,Manager Material Control. Supply Assurance and...,NaN,...,18,Manufacturing,18,Automotive,15,NaN,NaN,NaN,NaN,NaN
22,https://www.linkedin.com/in/moneer-azzam-58660b2/,Moneer,Azzam,Moneer Azzam,3rd,ACoAAAByNXYBngF7lqUjyi_7QybqaOV_MPzfgUY,SolarOne Solutions. Inc,https://www.linkedin.com/search/results/index/...,President/CEO,SolarOne Solutions Inc with its SO-Bright(R) T...,...,50,Strategic Planning,34,Renewable Energy,32,Attended night school thru Raytheon and Mobil ...,NaN,NaN,MoneerAzzam,NaN
23,https://www.linkedin.com/in/graham-sayers-5518...,Graham,Sayers,Graham Sayers,3rd,ACoAAABNNw0BzMdXovohdqpOAqZ8BIca_vMFmug,Caraustar,https://www.linkedin.com/company/26811/,CFO,NaN,...,11,Financial Reporting,7,Cost Accounting,4,NaN,NaN,NaN,NaN,NaN
24,https://www.linkedin.com/in/chrisazar/,Christopher,Azar,Christopher Azar,3rd,ACoAAAWivgABSuLY0KJ9SFVTLHxsskr2Ujw5rHQ,Adobe,https://www.linkedin.com/company/1480/,Senior Experience Designer. Lead,NaN,...,13,Typography,4,Graphic Design,35,NaN,NaN,NaN,ReptarAzar,NaN
25,https://www.linkedin.com/in/dayana-peguero-028...,Dayana,Peguero,Dayana Peguero,3rd,ACoAAB9RXaABVtNOLY6x1ibFpOt5RA3PHKzG-2Q,M S International. Inc.,https://www.linkedin.com/company/132468/,Corporate Human Resources Generalist,About M S International. Inc. Founded in 1975....,...,0,Benefits Administration,0,U.S. Family and Medical Leave Act (FMLA),0,NaN,NaN,NaN,NaN,NaN
26,https://www.linkedin.com/in/yi-ming-lin-a1a41793/,Yi-Ming,Lin,Yi-Ming Lin,åÊ,ACoAABPRJfYB-kyVx2vrhEw8KDIdrBe4DIWPR7k,NaN,https://www.linkedin.com/search/results/index/,Ceramic art,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,https://www.linkedin.com/in/dominicsuciu/,Dominic,Suciu,Dominic Suciu,3rd,ACoAAAB36V0BxexjA1CtkTiNJX1OGSsU8eIiB-0,Quantarium,https://www.linkedin.com/company/7232786/,Data Scientist/Consultant,Computer Vision. Mask-RCNN Image Analysis,...,39,Life Sciences,29,Assay Development,26,NaN,Courses in C. Java. Finance,NaN,NaN,NaN
28,https://www.linkedin.com/in/shuang-wu-28761111/,Shuang,Wu,Shuang Wu,3rd,ACoAAAJncUcBpku9TpPhBHGjvhTrtrzvzcjPF9o,Amazon,https://www.linkedin.com/company/1586/,Sr. Machine Learning Scientist,Machine learning research for Alexa.,...,3,Mathematical Modeling,2,Big Data,1,NaN,NaN,Valedictorian,NaN,NaN
29,https://www.linkedin.com/in/jianmin-xue-47766198/,Jianmin,Xue,Jianmin Xue,åÊ,ACoAABS991sBK-znvt8PtMgYWMbcjRQEXEXUwbU,University of Pittsburgh,https://www.linkedin.com/company/3461/,Research Assistant Professor,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,https://www.linkedin.com/in/piotr-dlugosz-8160...,Piotr,Dlugosz,Piotr Dlugosz,åÊ,ACoAAABd29IBkbeRQSAk64vKiQt50ddn5f-7NyY,Kraft Foods,https://www.linkedin.com/company/1511/,Application Services Manager,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
562,https://www.linkedin.com/in/ulrich-vogel-5231283/,Ulrich,Vogel,Ulrich Vogel,3rd,ACoAAACNVusBBIFSfvL0yu8zLw3tyQ7WlzEVHS8,profilingvalues,https://www.linkedin.com/search/results/index/...,Managing Director,NaN,...,10,Recruitment Advertising,6,Search,4,NaN,NaN,NaN,NaN,NaN
563,https://www.linkedin.com/in/su-hao-5a440b4b/,Su,Hao,Su Hao,åÊ,ACoAAAqPrYwBYlu7c_YfqlfLUB8Kp0xPf4R9ePY,ACII. INC.,https://www.linkedin.com/search/results/index/...,Senoir Engineer,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
564,https://www.linkedin.com/in/eun-hye-cho-06a78021/,Eun,Hye Cho,Eun Hye Cho,3rd,ACoAAASQLFIB-yL889NV4Hk0uk3LsQYsrnB6fbA,LOI,https://www.linkedin.com/company/20352/,Freelance Teacher / Coach for the Korean Langu...,#NAME?,...,7,Fine Art,6,Museum Collections,5,NaN,NaN,Exchange student for 1 year,NaN,NaN
565,https://www.linkedin.com/in/steve-beaudin-7924...,Steve,Beaudin,Steve Beaudin,3rd,ACoAAAKNgF4BZt-cdnNg3RJ4YBP0Ly6vP1Zw-qA,Qualcomm,https://www.linkedin.com/company/2017/,Manager / Principal Engineer,Lead great team of RF system. EM. Thermal. Mec...,...,23,CDMA,18,Telecommunications,12,NaN,B. Eng.,NaN,NaN,NaN
566,https://www.linkedin.com/in/joseph-george-935a...,Joseph,George,Joseph George,åÊ,ACoAABd24zkBxPV6RmTnbvHVNsI3cYVCmJft2zc,CordCase. LLC,https://www.linkedin.com/search/results/index/...,President & CEO,CordCase is the worlds 1st patented cell phone...,...,NaN,NaN,NaN,NaN,NaN,NaN,Associate's degree,NaN,NaN,NaN
567,https://www.linkedin.com/in/geoffrey-greene-0b...,Geoffrey,Greene,Geoffrey Greene,åÊ,ACoAAAhbTccBw_ywfrtwYGEodtEozfZVSG19nck,Knoxville Rider Education Program and IATSE Lo...,https://www.linkedin.com/search/results/index/...,Self employed,Knoxville Rider Education Program: Present mot...,...,10,Analysis,4,Inventory Management,3,NaN,Master of Music in Choral Conducting,NaN,NaN,NaN
568,https://www.linkedin.com/in/andrew-hawes-662a3...,Andrew,Hawes,Andrew Hawes,3rd,ACoAAAMAOOoB6NkZ-aPcH2mEMVjlGuGxN0AuZQE,The Housing Partnership Inc.,https://www.linkedin.com/company/1550296/,President,NaN,...,23,Mortgage Lending,22,Nonprofits,22,NaN,BA,NaN,NaN,NaN
569,https://www.linkedin.com/in/lboodaghians/,Lillian,Boodaghians,Lillian Boodaghians,3rd,ACoAABV4rM0BBTMM4ddXOuJOw8MjTAmK_P4PkuA,Fordham University School of Law,https://www.linkedin.com/company/7339/,JD Candidate,NaN,...,0,Scientific Writing,0,Technical Writing,2,Vice Provost Prize for Excellence - UCLA Under...,NaN,NaN,NaN,NaN
570,https://www.linkedin.com/in/wen-cheng-lai-8818...,Wen,Cheng Lai,Wen Cheng Lai,3rd,ACoAAAm9HaEBajzaxxt_WwJSDS_10cCBAyDFGpg,National Penghu University of Science and Tec...,https://www.linkedin.com/company/15137592/,Assistant Professor,NaN,...,23,Telecommunications,17,Project Management,16,Doctoral Dissertation: Modules Design and Inte...,Doctor of Philosophy (Ph.D.),Doctoral Dissertation: Impact of Key Facts on ...,eway1217,NaN
571,https://www.linkedin.com/in/dr-taghipour-118a6...,Dr,Taghipour,Dr Taghipour,åÊ,ACoAAAf8suQBd1HXTmZuOs45kwQJo4AW4wax7VA,medtronic,https://www.linkedin.com/company/1841/,medical doctor,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
572,https://www.linkedin.com/in/charlesblackledge/,Charles,Blackledge. P.E.. PMP,Charles Blackledge. P.E.. PMP,3rd,ACoAAAGD42IBXmLgMybA6gpUt9KEtyGSdbSSJWI,Entergy,https://www.linkedin.com/company/163640/,Senior Project Manager,Perform project cost and cash flow forecast. \...,...,28,Power Plants,28,Energy,20,- Worked part time at the Rec Center- Complete...,Master's,Completed MBA with 3.98 GPA.,NaN,NaN
573,https://www.linkedin.com/in/eric-williams-7a4b...,Eric,Williams,Eric Williams,åÊ,ACoAAAuQvGwBC4pLylbr7p9GSeTTG1xFZ6zpWLQ,Kansas City Missouri Police Department,https://www.linkedin.com/company/75687/,Police Officer,NaN,...,5,Loans,5,Financial Services,3,NaN,NaN,NaN,NaN,NaN
574,https://www.linkedin.com/in/chia-yen-yeh-a7841...,CHIA-YEN,YEH,CHIA-YEN YEH,3rd,ACoAAAe25jwB-7nnpDWsAtfa6hrlLvcxbSgQjPI,STAR BIT Innovation,https://www.linkedin.com/company/13739308/,Blockchain Business Development Manager,ÐÊ Meet business growth with the ambition of ...,...,4,Consumer Electronics,4,Industrial Design,4,Master Dissertation: Food Gap in International...,Bachelor's degree,Graduate Project: The Half & The Other ÛÒ Fur...,NaN,NaN
575,https://www.linkedin.com/in/yu-wen-liao-81b26284/,yu,wen liao,yu wen liao,åÊ,ACoAABHV0BcBkDXvRPr0fGoZtehY_HhHoOPTb_M,Gia-Jiu Enterprise MFG. Corporation,https://www.linkedin.com/search/results/index/...,Accountant,With 3 years experience in finance and account...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
576,https://www.linkedin.com/in/michaelzaczek/,Michael,Zaczek,Michael Zaczek,3rd,ACoAAAI7DYIBtjHpBvaNMB6QlOGZX_zlXS4i2Zs,SAP,https://www.linkedin.com/company/1115/,Account Executive - Northeast General Business,Responsible for SAPÛªs entire solution portfo...,...,22,CRM,18,Professional Services,8,NaN,NaN,NaN,MichaelZaczek,NaN
577,https://www.linkedin.com/in/andrey-muraviev-7b...,Andrey,Muraviev,Andrey Muraviev,åÊ,ACoAAAMd1fUBMSs-H3eT00sR31Odj8sKOjRJZhA,University of Central Florida - CREOL. College...,https://www.linkedin.com/search/results/index/...,Research Scientist,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
578,https://www.linkedin.com/in/dougmaukonen/,Doug,Maukonen,Doug Maukonen,åÊ,ACoAAABsUBUB7EGcRP5OP5VKk_uMuaNtPKuT2f8,Univeristy of Central Florida. Center for Mico...,https://www.linkedin.com/search/results/index/...,Systems Engineer / Electrical Engineer,The UCF Department of Physics Planetary Scienc...,...,3,Photography,3,Laboratory,3,I am continuing coursework in the planetary sc...,AA,NaN,NaN,NaN
579,https://www.linkedin.com/in/jieyu-yang/,Jieyu,(Jessica) Yang,Jieyu (Jessica) Yang,3rd,ACoAAAjHBV8BdmpvNbiQlNL7uXV6YfeqphUAcwc,Google,https://www.linkedin.com/company/1441/,UX Contractor,NaN,...,13,Typography,10,Project Management,12,NaN,NaN,NaN,NaN,NaN
580,https://www.linkedin.com/in/yu-cheng-huang-469...,Yu-Cheng,Huang,Yu-Cheng Huang,3rd,ACoAAAQzbBEBkrl1ROfVWOZ2p9JJFw_XXvRpZiw,Facebook,https://www.linkedin.com/company/10667/,Software Engineer,FBLearner Inference Platform,...,5,Python,8,C++,6,NaN,BS,NaN,NaN,NaN
581,https://www.linkedin.com/in/junianioffe/,Junian,Ioffe,Junian Ioffe,3rd,ACoAABAiiKwByN9Y3nAVobMpYOv3P_slbm6BlEs,a4 Media,https://www.linkedin.com/company/18622372/,Product Manager - Media Apps,a4 Media is the rapidly-growing advertising an...,...,33,Agile Methodologies,9,Data Analysis,18,Ð¼Software Product Management 12-Month Cumula...,Bachelor of Science (B.Sc.),NaN,NaN,NaN
582,https://www.linkedin.com/in/craig-brodersen-52...,Craig,Brodersen,Craig Brodersen,åÊ,ACoAAAdpjWsB6RLqjpHDE0CcJD49AudAPq576V0,Seltec Inc.,https://www.linkedin.com/search/results/index/...,Investment Casting Consultant,NaN,...,9,Continuous Improvement,9,Quality Management,9,NaN,NaN,NaN,NaN,NaN
583,https://www.linkedin.com/in/sergey-tsyukalo-38...,Sergey,Tsyukalo,Sergey Tsyukalo,åÊ,ACoAAB68PZQBDvb6V8ZNSXL2_0DMMpBhvFrkZBI,Gonzaga University,https://www.linkedin.com/company/14646/,Painter,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
584,https://www.linkedin.com/in/christos-tsironis-...,Christos,Tsironis,Christos Tsironis,åÊ,ACoAAAqKOiQBVHctwIJ5S0Or5VxGWPC9kqQXkqs,St. Mary's Hospital Imperial College Healthcar...,https://www.linkedin.com/search/results/index/...,Consultant General. Upper Gastrointestinal & B...,NaN,...,11,Medical Education,11,Surgery,9,NaN,Doctor of Medicine (MD),NaN,NaN,NaN
585,https://www.linkedin.com/in/dr-charles-stewart...,Dr,Charles Stewart,Dr Charles Stewart,3rd,ACoAAAErxDEBKyCwA3eji9hDbe6MTM3yhB2hNec,California Association of Dental Plans,https://www.linkedin.com/search/results/index/...,Board Member,NaN,...,55,Practice Management,41,Strategic Planning,40,NaN,NaN,NaN,NaN,NaN
586,https://www.linkedin.com/in/christopher-tridic...,Christopher,Tridico,Christopher Tridico,3rd,ACoAAAr1krIBCXYLJ9Qgt8YGXij9to-8R2OC0RQ,Accenture,https://www.linkedin.com/company/1033/,Managing Director,NaN,...,3,Electrical Engineering,2,Software Development,3,NaN,NaN,NaN,NaN,NaN
587,https://www.linkedin.com/in/weisong44/,Wei,Song,Wei Song,3rd,ACoAAAGO104BWRVI2lkZWAxbO_Eoc3BeAb5_TEs,LinkedIn,https://www.linkedin.com/company/1337/,Sr Staff Engineer,Data infrastructure and streaming - Databus/Br...,...,29,System Architecture,26,TCP/IP,26,NaN,Bachelor,NaN,NaN,NaN
588,https://www.linkedin.com/in/baronsandra/,Sandra,Baron,Sandra Baron,åÊ,ACoAAAAGYQIBwy8DYWhJHoU-s8JhJM4VkCRQxo0,BCC - Baron Coaching & Consulting,https://www.linkedin.com/search/results/index/...,Coach. Consultant. Facilitator,#NAME?,...,5,Business Development,5,Telecommunications,3,NaN,NaN,NaN,NaN,NaN
589,https://www.linkedin.com/in/olivermhaynold/,Oliver,M. Haynold. Ph.D. CFA,Oliver M. Haynold. Ph.D. CFA,3rd,ACoAAAC5iFMBupJKOmHEeBkKppKeUco_Cczpn28,CME Group,https://www.linkedin.com/company/5499/,Director Pricing & Incentives,Designing and implementing pricing and incenti...,...,7,Financial Services,7,Financial Markets,6,NaN,Ph.D.,NaN,NaN,NaN
590,https://www.linkedin.com/in/randall-wilson-475...,Randall,Wilson,Randall Wilson,3rd,ACoAAABD59kBecT2rFnmIHudocrCC-apRaqSgj0,BrightEdge,https://www.linkedin.com/company/1279563/,Vice President. Customer Success,NaN,...,47,SEO,33,Online Advertising,30,Received MBA with focus on entrepreneurship an...,BA,Conducted linguistic research and was paid to ...,NaN,NaN

In [93]:
# merge result and final on column 'linkedinProfile'
merged = pd.merge(final, result, how='left', left_on='linkedinProfile', right_on='linkedinProfile')

In [97]:
# drop duplicate indexes (only keep first) to correct for inconsistency
merged = merged.drop_duplicates(subset = ['original_index'])

In [98]:
merged

,original_index,appl_id,inventor_name_first,inventor_name_middle,inventor_name_last,inventor_rank,inventor_region_code,inventor_country_code,inventor_country_name,inventor_address_type,...,endorsement4,skill5,endorsement5,skill6,endorsement6,schoolDescription,schoolDegree2,schoolDescription2,twitter,mail
0,0,13199870,Durand,Kevin,Dickerson,1,KS,US,UNITED STATES,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,13199870,Lawrence,Derwood,Kenemore,2,KS,US,UNITED STATES,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,13261475,Stefanos,NaN,Ntoukolianos,1,NaN,GR,GREECE,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,5,13261723,Mukul,Chandra,Gope,1,NaN,IN,INDIA,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,7,13261789,Mitsutoshi,NaN,Sugawara,1,NaN,JP,JAPAN,postal,...,1,IC,0,LSI¬_¬ö,1,NaN,NaN,NaN,NaN,NaN
63,9,13261809,Georgios,NaN,Mavroeidis,1,NaN,GR,GREECE,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,11,13261831,Lorena,NaN,Dordan,1,CA,US,UNITED STATES,residence,...,1,Patents,0,Product Design,0,Master Degree: International Relations.As of 2...,Bachelor's Degree,Bilingual in English and SpanishConcentration ...,NaN,NaN
65,13,13261848,Joshua (Josh),Noel,Hogan,1,CA,US,UNITED STATES,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,15,13356632,Kai,NaN,Tao,1,NaN,CN,CHINA,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,16,13391446,Eckhard,NaN,Lohde,2,NaN,DE,GERMANY,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,17,13391446,Olaf,NaN,Christiansen,1,NaN,DE,GERMANY,postal,...,7,HR Consulting,4,Recruiting,4,NaN,NaN,NaN,NaN,NaN
98,19,13426684,David,NaN,Hirshberg,1,NaN,IL,ISRAEL,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,21,13438140,Mark,Macdonough,Robinson,1,MA,US,UNITED STATES,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,23,13442888,Chaloke,NaN,Pungtrakul,1,NaN,TH,THAILAND,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,25,13465206,Steven,B.,Tracy,1,ME,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,27,13465375,Liu,NaN,Yang,1,CA,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,29,13465375,Fang,NaN,Sheng,2,CA,US,UNITED STATES,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,30,13467009,David,J.,Mishelevich,1,CA,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,32,13474326,Norman,Scott,Peckenpaugh,1,WA,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,36,13481539,Laszlo,NaN,Redey,1,IL,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,38,13482342,Michael,Robert,White,1,CA,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,40,13484165,Sergey,NaN,Anikin,1,CA,US,NaN,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,42,13486438,Benjamin,NaN,Pouladian,2,CA,US,UNITED STATES,residence,...,77,Business Development,52,Start-ups,47,Participated in cutting edge nano-scale optica...,NaN,NaN,getDECO,NaN
255,43,13486438,Saman,NaN,Sinai,1,CA,US,UNITED STATES,residence,...,59,Manufacturing,54,Competitive Analysis,44,NaN,Bacholor's Degree,NaN,NaN,NaN
256,45,13487252,Yong-Kyu,NaN,Jung,1,TX,US,UNITED STATES,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,47,13490478,Gabriel,NaN,Yavor,1,NaN,IL,ISRAEL,residence,...,19,R&D,15,Optical Fiber,13,NaN,MsC,NaN,NaN,NaN
258,49,13494995,Shih-Lin,NaN,Chang,3,NaN,TW,TAIWAN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,50,13494995,Bin-Juine,NaN,Huang,1,NaN,TW,TAIWAN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,52,13494995,Jong-Fu,NaN,Yeh,2,NaN,TW,TAIWAN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,53,13500071,Arun,NaN,Jain,1,NJ,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26256,3088,14217448,Christopher,V.,Beckman,1,NY,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26286,3094,14217526,Chiedo,NaN,Ohanyerenwa,2,DC,US,UNITED STATES,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26316,3095,14217526,James,NaN,Clarke,1,DC,US,NaN,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26346,3121,14222622,Ryan,Patrick,Rye,1,GA,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26376,3123,14222634,Mariana,NaN,Goldhamer,1,NaN,IL,NaN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26406,3153,14244439,Christos,NaN,Tsironis,1,NaN,CA,CANADA,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26436,3185,14261385,Lothar,NaN,Pantel,1,NaN,DE,NaN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26466,3204,14264014,Alexander,Mikhailovich,Shukh,1,CA,US,UNITED STATES,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26496,3208,14264062,Da Hao,NaN,Wu,1,NaN,TW,TAIWAN,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26526,3228,14269144,Scott,NaN,Sullivan,1,CA,US,NaN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26556,3230,14269178,Ryan,Patrick,Rye,1,GA,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26586,3266,14287342,Raphael,V.,Lupo,2,VA,US,NaN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26616,3267,14287342,Donald,B.,Ardell,1,FL,US,NaN,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26646,3282,14290969,Alexander,Mikhailovich,Shukh,1,CA,US,NaN,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26676,3338,14311350,Gaurav,NaN,Bazaz,1,NJ,US,NaN,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26706,3364,14318690,Steven,Sounyoung,Yu,1,MD,US,NaN,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26736,3372,14318722,Rajeev,Conrad,Nongpiur,1,NaN,CA,NaN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26766,3394,14327578,Chen-Wei,NaN,Hsu,1,TW,TW,NaN,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26796,3396,14328673,Alexander,Mikhailovich,Shukh,1,CA,US,NaN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26826,3430,14355218,Pawel,NaN,Darlak,2,NaN,PL,POLAND,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26856,3431,14355218,Piotr,NaN,Dlugosz,3,NaN,PL,POLAND,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26886,3433,14355218,Jerzy,NaN,Sobczak,1,NaN,PL,POLAND,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26916,3436,14355229,Pawel,NaN,Darlak,2,NaN,PL,POLAND,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26946,3437,14355229,Piotr,NaN,Dlugosz,3,NaN,PL,POLAND,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26976,3438,14355229,Jerzy,NaN,Sobczak,1,NaN,PL,POLAND,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27006,3497,14465872,Daniel,A.,Katz,1,NaN,IL,ISRAEL,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27036,3507,14471111,Christos,NaN,Tsironis,1,NaN,CA,NaN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27066,3536,14508107,Jiali,NaN,Wu,1,NY,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27096,3539,14515729,Jae,Hyun,Lim,1,NJ,US,UNITED STATES,postal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27126,3543,14523851,Fariborz,NaN,Taghipour,1,NaN,CA,NaN,residence,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
merged = merged.replace('nan', '', regex = True)

# removing inconsistencies
merged = merged.replace('https://www.linkedin.com/in/ethanlam', '', regex = True)
merged = merged.replace('ethanlam', '', regex = True)

merged.to_csv('final_with_data.csv', quoting=csv.QUOTE_ALL)

In [72]:
result.to_csv('results_cleaned.csv', quoting=csv.QUOTE_ALL)

In [171]:
# create csv of links that need to be scrapped
links = merged[['linkedinProfile','fullName']]
links = links.replace(np.nan, '', regex = True)
links = links[links['fullName'] == ""]

In [174]:
# drop duplicate links
links = links.drop_duplicates()

In [176]:
links.to_csv('scrap_links.csv', sep = ',')

# Second group of links

In [361]:
# Phantombuster file (pt2)
result_pt2 = pd.read_csv("phantombuster_pt2.csv", encoding = "ISO-8859-1", delimiter = ',', dtype = object)

# replace all commas with periods to put into csv later
result_pt2 = result_pt2.stack().str.replace(',','.').unstack()

# cast links as strings
result_pt2['linkedinProfile'] = result_pt2['linkedinProfile'].astype(str)

# replace NaNs with empty strings
result_pt2 = result_pt2 .replace(np.nan, '', regex = True)
result_pt2  = result_pt2 .replace('nan', '', regex = True)

result_pt2.to_csv('results_cleaned_pt2.csv', quoting = csv.QUOTE_ALL)

In [362]:
merged = pd.read_csv('final_with_data.csv', encoding = "ISO-8859-1", delimiter = ',', dtype = object)

# replace NaNs with empty strings
merged = merged.replace(np.nan, '', regex = True)
merged = merged.replace('nan', '', regex = True)

In [363]:
# merge result_pt2 and merged on column 'linkedinProfile'

merged = pd.merge(merged, result_pt2, how='left', left_on = 'linkedinProfile', right_on = 'linkedinProfile')

In [364]:
columns = [
       'firstName', 'lastName', 'fullName', 'connectionDegree', 'vmid',
       'company', 'companyUrl', 'jobTitle', 'jobDescription', 'location',
       'company2', 'companyUrl2', 'jobTitle2', 'location2', 'school',
       'schoolUrl', 'schoolDateRange', 'school2', 'schoolUrl2',
       'schoolDateRange2', 'baseUrl', 'profileId', 'timestamp', 'description',
       'imgUrl', 'jobDescription2', 'schoolDegree', 'schoolDegreeSpec',
       'schoolDegreeSpec2', 'allSkills', 'skill1', 'endorsement1', 'skill2',
       'endorsement2', 'skill3', 'endorsement3', 'skill4', 'endorsement4',
       'skill5', 'endorsement5', 'skill6', 'endorsement6', 'schoolDescription',
       'schoolDegree2', 'schoolDescription2', 'twitter', 'mail']

for col in columns:
    merged[col] = merged[col + '_x'].map(str) + merged[col + '_y'].map(str)

In [368]:
merged = merged.replace('nan', '', regex = True)

for col in columns:
    merged = merged.drop(col + '_x', axis = 1)
    merged = merged.drop(col + '_y', axis = 1)

In [373]:
# drop duplicate indexes (only keep first) to correct for inconsistency
merged = merged.drop_duplicates(subset = ['original_index'])

cols_to_drop = ['linkedinSalesNavigatorUrl','timestamp','mutualConnectionsUrl', 'connectionDegree']

# drop irrelevant columns
merged = merged.drop(cols_to_drop, axis = 1)

In [377]:
# rename columns for ease of understanding
merged = merged.rename({'fullName':'linkedin_fullName', 'firstName':'linkedin_firstName', 'lastName':'linkedin_lastName'})

In [378]:
merged.to_csv('final_results.csv', quoting = csv.QUOTE_ALL)

In [381]:
merged.columns

Index(['original_index', 'appl_id', 'inventor_name_first',
       'inventor_name_middle', 'inventor_name_last', 'inventor_rank',
       'inventor_region_code', 'inventor_country_code',
       'inventor_country_name', 'inventor_address_type', '_merge', 'state',
       'linkedinProfile', 'Maybe', 'Duplicates', 'unique', 'full_name',
       'firstName', 'lastName', 'fullName', 'vmid', 'company', 'companyUrl',
       'jobTitle', 'jobDescription', 'location', 'company2', 'companyUrl2',
       'jobTitle2', 'location2', 'school', 'schoolUrl', 'schoolDateRange',
       'school2', 'schoolUrl2', 'schoolDateRange2', 'baseUrl', 'profileId',
       'timestamp', 'description', 'imgUrl', 'jobDescription2', 'schoolDegree',
       'schoolDegreeSpec', 'schoolDegreeSpec2', 'allSkills', 'skill1',
       'endorsement1', 'skill2', 'endorsement2', 'skill3', 'endorsement3',
       'skill4', 'endorsement4', 'skill5', 'endorsement5', 'skill6',
       'endorsement6', 'schoolDescription', 'schoolDegree2',
       'schoolDescription2', 'twitter', 'mail'],
      dtype='object')

# Third group of links

In [18]:
# Phantombuster file (pt3)
result_pt3 = pd.read_csv("phantombuster_pt3.csv", encoding = "ISO-8859-1", delimiter = ',', dtype = object)

# replace all commas with periods to put into csv later
result_pt3 = result_pt3.stack().str.replace(',','.').unstack()

# cast links as strings
result_pt3['linkedinProfile'] = result_pt3['linkedinProfile'].astype(str)

# # replace NaNs with empty strings
# result_pt3 = result_pt3.replace(np.nan, '', regex = True)
# result_pt3  = result_pt3.replace('nan', '', regex = True)

result_pt3.to_csv('results_cleaned_pt3.csv', quoting = csv.QUOTE_ALL)

In [19]:
final = pd.read_csv('final_results_updated.csv', encoding = "ISO-8859-1", delimiter = ',', dtype = object)

# replace NaNs with empty strings
final = final.replace(np.nan, '', regex = True)

In [20]:
final

,original_index,appl_id,inventor_name_first,inventor_name_middle,inventor_name_last,inventor_rank,inventor_region_code,inventor_country_code,inventor_country_name,inventor_address_type,...,endorsement4,skill5,endorsement5,skill6,endorsement6,schoolDescription,schoolDegree2,schoolDescription2,twitter,mail
0,0,13199870,Durand,Kevin,Dickerson,1,KS,US,UNITED STATES,residence,...,,,,,,,,,,
1,2,13199870,Lawrence,Derwood,Kenemore,2,KS,US,UNITED STATES,residence,...,10,Social Media,8,Marketing Strategy,5,,Paramedic,,statMedDisp,
2,3,13261475,Stefanos,,Ntoukolianos,1,,GR,GREECE,postal,...,,,,,,,,,,
3,5,13261723,Mukul,Chandra,Gope,1,,IN,INDIA,postal,...,,,,,,,,,,
4,7,13261789,Mitsutoshi,,Sugawara,1,,JP,JAPAN,postal,...,1,IC,0,LSI_´____´____,1,,,,,
5,9,13261809,Georgios,,Mavroeidis,1,,GR,GREECE,residence,...,,,,,,,,,,
6,11,13261831,Lorena,,Dordan,1,CA,US,UNITED STATES,residence,...,1,Patents,0,Product Design,0,Master Degree: International Relations.As of 2...,Bachelor's Degree,Bilingual in English and SpanishConcentration ...,,
7,13,13261848,Joshua (Josh),Noel,Hogan,1,CA,US,UNITED STATES,residence,...,,,,,,,,,,
8,16,13391446,Eckhard,,Lohde,2,,DE,GERMANY,residence,...,,,,,,,,,,
9,17,13391446,Olaf,,Christiansen,1,,DE,GERMANY,postal,...,7,HR Consulting,4,Recruiting,4,,,,,
10,19,13426684,David,,Hirshberg,1,,IL,ISRAEL,residence,...,8,Entrepreneurship,7,Digital Signal Processors,5,,M.Sc.EE,,,
11,21,13438140,Mark,Macdonough,Robinson,1,MA,US,UNITED STATES,residence,...,17,Energy Efficiency,15,Photovoltaics,13,,,,,
12,23,13442888,Chaloke,,Pungtrakul,1,,TH,THAILAND,residence,...,,,,,,,,,,
13,25,13465206,Steven,B.,Tracy,1,ME,US,UNITED STATES,postal,...,0,Woodworking,0,Plumbing,0,,,,,
14,27,13465375,Liu,,Yang,1,CA,US,UNITED STATES,postal,...,,,,,,,,,,
15,29,13465375,Fang,,Sheng,2,CA,US,UNITED STATES,residence,...,,,,,,,,,,
16,32,13474326,Norman,Scott,Peckenpaugh,1,WA,US,UNITED STATES,postal,...,,,,,,,,,,
17,36,13481539,Laszlo,,Redey,1,IL,US,UNITED STATES,postal,...,,,,,,,,,,
18,38,13482342,Michael,Robert,White,1,CA,US,UNITED STATES,postal,...,11,Computer Graphics,5,Project Management,5,https://bootcamp.berkeley.edu/coding/curriculum,The Web Developer Bootcamp,HTML5CSS3JavaScriptBootstrapSemanticUIDOM Mani...,joomla_go,
19,40,13484165,Sergey,,Anikin,1,CA,US,,postal,...,,,,,,,,,,
20,42,13486438,Benjamin,,Pouladian,2,CA,US,UNITED STATES,residence,...,77,Business Development,52,Start-ups,47,Participated in cutting edge o-scale optical r...,,,getDECO,
21,43,13486438,Saman,,Sinai,1,CA,US,UNITED STATES,residence,...,59,Manufacturing,54,Competitive Analysis,44,,Bacholor's Degree,,,
22,45,13487252,Yong-Kyu,,Jung,1,TX,US,UNITED STATES,residence,...,,,,,,,,,,
23,47,13490478,Gabriel,,Yavor,1,,IL,ISRAEL,residence,...,19,R&D,15,Optical Fiber,13,,MsC,,,
24,49,13494995,Shih-Lin,,Chang,3,,TW,TAIWAN,residence,...,,,,,,,,,,
25,50,13494995,Bin-Juine,,Huang,1,,TW,TAIWAN,residence,...,,,,,,,,,,
26,52,13494995,Jong-Fu,,Yeh,2,,TW,TAIWAN,residence,...,,,,,,,,,,
27,53,13500071,Arun,,Jain,1,NJ,US,UNITED STATES,postal,...,,,,,,,,,,
28,55,13506737,Edward,Ludwig,Blendermann,1,FL,US,UNITED STATES,residence,...,,,,,,,,,,
29,57,13507297,Michael,Steven,Hargett,1,OR,US,UNITED STATES,postal,...,16,Start-ups,15,Sales,11,,Business Administration Management,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1925,3062,14215026,Alfred,M.,Haas,1,NJ,US,,residence,...,,,,,,,,,,
1926,3078,14216876,Alfred,M.,Haas,1,NJ,US,,residence,...,,,,,,,,,,
1927,3088,14217448,Christopher,V.,Beckman,1,NY,US,UNITED STATES,postal,...,,,,,,,,,,
1928,3094,14217526,Chiedo,,Ohanyerenwa,2,DC,US,UNITED STATES,residence,...,,,,,,,,,,
1929,3095,14217526,James,,Clarke,1,DC,US,,postal,...,,,,,,,,,,
1930,3121,14222622,Ryan,Patrick,Rye,1,GA,US,UNITED STATES,postal,...,,,,,,,,,,
1931,3123,14222634,Mariana,,Goldhamer,1,,IL,,residence,...,,,,,,,,,,
1932,3153,14244439,Christos,,Tsironis,1,,CA,CANADA,residence,...,,,,,,,,,,
1933,3185,14261385,Lothar,,Pantel,1,,DE,,residence,...,,,,,,,,,,
1934,3204,14264014,Alexander,Mikhailovich,Shukh,1,CA,US,UNITED STATES,residence,...,,,,,,,,,,
1935,3208,14264062,Da Hao,,Wu,1,,TW,TAIWAN,postal,...,,,,,,,,,,
1936,3228,14269144,Scott,,Sullivan,1,CA,US,,residence,...,,,,,,,,,,
1937,3230,14269178,Ryan,Patrick,Rye,1,GA,US,UNITED STATES,postal,...,,,,,,,,,,
1938,3266,14287342,Raphael,V.,Lupo,2,VA,US,,residence,...,,,,,,,,,,
1939,3267,14287342,Donald,B.,Ardell,1,FL,US,,postal,...,,,,,,,,,,
1940,3282,14290969,Alexander,Mikhailovich,Shukh,1,CA,US,,postal,...,,,,,,,,,,
1941,3338,14311350,Gaurav,,Bazaz,1,NJ,US,,postal,...,,,,,,,,,,
1942,3364,14318690,Steven,Sounyoung,Yu,1,MD,US,,postal,...,,,,,,,,,,
1943,3396,14328673,Alexander,Mikhailovich,Shukh,1,CA,US,,residence,...,,,,,,,,,,
1944,3430,14355218,Pawel,,Darlak,2,,PL,POLAND,postal,...,,,,,,,,,,
1945,3431,14355218,Piotr,,Dlugosz,3,,PL,POLAND,postal,...,,,,,,,,,,
1946,3433,14355218,Jerzy,,Sobczak,1,,PL,POLAND,postal,...,,,,,,,,,,
1947,3436,14355229,Pawel,,Darlak,2,,PL,POLAND,postal,...,,,,,,,,,,
1948,3437,14355229,Piotr,,Dlugosz,3,,PL,POLAND,residence,...,,,,,,,,,,
1949,3438,14355229,Jerzy,,Sobczak,1,,PL,POLAND,postal,...,,,,,,,,,,
1950,3497,14465872,Daniel,A.,Katz,1,,IL,ISRAEL,residence,...,,,,,,,,,,
1951,3507,14471111,Christos,,Tsironis,1,,CA,,residence,...,,,,,,,,,,
1952,3536,14508107,Jiali,,Wu,1,NY,US,UNITED STATES,postal,...,,,,,,,,,,
1953,3539,14515729,Jae,Hyun,Lim,1,NJ,US,UNITED STATES,postal,...,,,,,,,,,,
1954,3543,14523851,Fariborz,,Taghipour,1,,CA,,residence,...,,,,,,,,,,

In [21]:
final = pd.merge(final, result_pt3, how='left', left_on = 'linkedinProfile', right_on = 'linkedinProfile')

In [22]:
final = final.replace(np.nan, '', regex = True)

In [23]:
columns = [
       'company', 'companyUrl', 'jobTitle', 'jobDescription', 'location',
       'company2', 'companyUrl2', 'jobTitle2', 'location2', 'school',
       'schoolUrl', 'schoolDateRange', 'school2', 'schoolUrl2',
       'schoolDateRange2', 'profileId', 'description',
       'imgUrl', 'jobDescription2', 'schoolDegree', 'schoolDegreeSpec',
       'schoolDegreeSpec2', 'allSkills', 'skill1', 'endorsement1', 'skill2',
       'endorsement2', 'skill3', 'endorsement3', 'skill4', 'endorsement4',
       'skill5', 'endorsement5', 'skill6', 'endorsement6', 'schoolDescription',
       'schoolDegree2', 'schoolDescription2', ]

for col in columns:
    final[col] = final[col + '_x'].map(str) + final[col + '_y'].map(str)

In [24]:
final

,original_index,appl_id,inventor_name_first,inventor_name_middle,inventor_name_last,inventor_rank,inventor_region_code,inventor_country_code,inventor_country_name,inventor_address_type,...,endorsement3,skill4,endorsement4,skill5,endorsement5,skill6,endorsement6,schoolDescription,schoolDegree2,schoolDescription2
0,0,13199870,Durand,Kevin,Dickerson,1,KS,US,UNITED STATES,residence,...,,,,,,,,,,
1,2,13199870,Lawrence,Derwood,Kenemore,2,KS,US,UNITED STATES,residence,...,12,Renewable Energy,10,Social Media,8,Marketing Strategy,5,,Paramedic,
2,3,13261475,Stefanos,,Ntoukolianos,1,,GR,GREECE,postal,...,,,,,,,,,,
3,5,13261723,Mukul,Chandra,Gope,1,,IN,INDIA,postal,...,,,,,,,,,,
4,7,13261789,Mitsutoshi,,Sugawara,1,,JP,JAPAN,postal,...,1,ASIC,1,IC,0,LSI_´____´____,1,,,
5,9,13261809,Georgios,,Mavroeidis,1,,GR,GREECE,residence,...,,,,,,,,,,
6,11,13261831,Lorena,,Dordan,1,CA,US,UNITED STATES,residence,...,9,International Relations,1,Patents,0,Product Design,0,Master Degree: International Relations.As of 2...,Bachelor's Degree,Bilingual in English and SpanishConcentration ...
7,13,13261848,Joshua (Josh),Noel,Hogan,1,CA,US,UNITED STATES,residence,...,,,,,,,,,,
8,16,13391446,Eckhard,,Lohde,2,,DE,GERMANY,residence,...,,,,,,,,,,
9,17,13391446,Olaf,,Christiansen,1,,DE,GERMANY,postal,...,2,Performance Management,7,HR Consulting,4,Recruiting,4,,,
10,19,13426684,David,,Hirshberg,1,,IL,ISRAEL,residence,...,8,System Architecture,8,Entrepreneurship,7,Digital Signal Processors,5,,M.Sc.EE,
11,21,13438140,Mark,Macdonough,Robinson,1,MA,US,UNITED STATES,residence,...,21,Energy,17,Energy Efficiency,15,Photovoltaics,13,,,
12,23,13442888,Chaloke,,Pungtrakul,1,,TH,THAILAND,residence,...,,,,,,,,,,
13,25,13465206,Steven,B.,Tracy,1,ME,US,UNITED STATES,postal,...,0,Carpentry,0,Woodworking,0,Plumbing,0,,,
14,27,13465375,Liu,,Yang,1,CA,US,UNITED STATES,postal,...,,,,,,,,,,
15,29,13465375,Fang,,Sheng,2,CA,US,UNITED STATES,residence,...,,,,,,,,,,
16,32,13474326,Norman,Scott,Peckenpaugh,1,WA,US,UNITED STATES,postal,...,,,,,,,,,,
17,36,13481539,Laszlo,,Redey,1,IL,US,UNITED STATES,postal,...,,,,,,,,,,
18,38,13482342,Michael,Robert,White,1,CA,US,UNITED STATES,postal,...,13,E-commerce,11,Computer Graphics,5,Project Management,5,https://bootcamp.berkeley.edu/coding/curriculum,The Web Developer Bootcamp,HTML5CSS3JavaScriptBootstrapSemanticUIDOM Mani...
19,40,13484165,Sergey,,Anikin,1,CA,US,,postal,...,,,,,,,,,,
20,42,13486438,Benjamin,,Pouladian,2,CA,US,UNITED STATES,residence,...,97,Venture Capital,77,Business Development,52,Start-ups,47,Participated in cutting edge o-scale optical r...,,
21,43,13486438,Saman,,Sinai,1,CA,US,UNITED STATES,residence,...,65,Product Development,59,Manufacturing,54,Competitive Analysis,44,,Bacholor's Degree,
22,45,13487252,Yong-Kyu,,Jung,1,TX,US,UNITED STATES,residence,...,,,,,,,,,,
23,47,13490478,Gabriel,,Yavor,1,,IL,ISRAEL,residence,...,19,Physics,19,R&D,15,Optical Fiber,13,,MsC,
24,49,13494995,Shih-Lin,,Chang,3,,TW,TAIWAN,residence,...,,,,,,,,,,
25,50,13494995,Bin-Juine,,Huang,1,,TW,TAIWAN,residence,...,,,,,,,,,,
26,52,13494995,Jong-Fu,,Yeh,2,,TW,TAIWAN,residence,...,,,,,,,,,,
27,53,13500071,Arun,,Jain,1,NJ,US,UNITED STATES,postal,...,,,,,,,,,,
28,55,13506737,Edward,Ludwig,Blendermann,1,FL,US,UNITED STATES,residence,...,,,,,,,,,,
29,57,13507297,Michael,Steven,Hargett,1,OR,US,UNITED STATES,postal,...,19,Electronics,16,Start-ups,15,Sales,11,,Business Administration Management,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1925,3062,14215026,Alfred,M.,Haas,1,NJ,US,,residence,...,,,,,,,,,,
1926,3078,14216876,Alfred,M.,Haas,1,NJ,US,,residence,...,,,,,,,,,,
1927,3088,14217448,Christopher,V.,Beckman,1,NY,US,UNITED STATES,postal,...,,,,,,,,,,
1928,3094,14217526,Chiedo,,Ohanyerenwa,2,DC,US,UNITED STATES,residence,...,,,,,,,,,,
1929,3095,14217526,James,,Clarke,1,DC,US,,postal,...,,,,,,,,,,
1930,3121,14222622,Ryan,Patrick,Rye,1,GA,US,UNITED STATES,postal,...,,,,,,,,,,
1931,3123,14222634,Mariana,,Goldhamer,1,,IL,,residence,...,,,,,,,,,,
1932,3153,14244439,Christos,,Tsironis,1,,CA,CANADA,residence,...,,,,,,,,,,
1933,3185,14261385,Lothar,,Pantel,1,,DE,,residence,...,,,,,,,,,,
1934,3204,14264014,Alexander,Mikhailovich,Shukh,1,CA,US,UNITED STATES,residence,...,,,,,,,,,,
1935,3208,14264062,Da Hao,,Wu,1,,TW,TAIWAN,postal,...,,,,,,,,,,
1936,3228,14269144,Scott,,Sullivan,1,CA,US,,residence,...,,,,,,,,,,
1937,3230,14269178,Ryan,Patrick,Rye,1,GA,US,UNITED STATES,postal,...,,,,,,,,,,
1938,3266,14287342,Raphael,V.,Lupo,2,VA,US,,residence,...,,,,,,,,,,
1939,3267,14287342,Donald,B.,Ardell,1,FL,US,,postal,...,,,,,,,,,,
1940,3282,14290969,Alexander,Mikhailovich,Shukh,1,CA,US,,postal,...,,,,,,,,,,
1941,3338,14311350,Gaurav,,Bazaz,1,NJ,US,,postal,...,,,,,,,,,,
1942,3364,14318690,Steven,Sounyoung,Yu,1,MD,US,,postal,...,,,,,,,,,,
1943,3396,14328673,Alexander,Mikhailovich,Shukh,1,CA,US,,residence,...,,,,,,,,,,
1944,3430,14355218,Pawel,,Darlak,2,,PL,POLAND,postal,...,,,,,,,,,,
1945,3431,14355218,Piotr,,Dlugosz,3,,PL,POLAND,postal,...,,,,,,,,,,
1946,3433,14355218,Jerzy,,Sobczak,1,,PL,POLAND,postal,...,,,,,,,,,,
1947,3436,14355229,Pawel,,Darlak,2,,PL,POLAND,postal,...,,,,,,,,,,
1948,3437,14355229,Piotr,,Dlugosz,3,,PL,POLAND,residence,...,,,,,,,,,,
1949,3438,14355229,Jerzy,,Sobczak,1,,PL,POLAND,postal,...,,,,,,,,,,
1950,3497,14465872,Daniel,A.,Katz,1,,IL,ISRAEL,residence,...,,,,,,,,,,
1951,3507,14471111,Christos,,Tsironis,1,,CA,,residence,...,,,,,,,,,,
1952,3536,14508107,Jiali,,Wu,1,NY,US,UNITED STATES,postal,...,,,,,,,,,,
1953,3539,14515729,Jae,Hyun,Lim,1,NJ,US,UNITED STATES,postal,...,,,,,,,,,,
1954,3543,14523851,Fariborz,,Taghipour,1,,CA,,residence,...,,,,,,,,,,

In [25]:
final.to_csv('checking.csv', quoting = csv.QUOTE_ALL)

In [15]:
# final with correct links
final = pd.read_csv("final.csv", encoding = "ISO-8859-1", delimiter = ',', dtype = object)

In [16]:
final = final.replace(np.nan, '', regex = True)

In [17]:
count = 0

for index, row in final.iterrows():
    url = final['linkedinProfile'][index]
    if url[-1:] != '/':
        print(url)
        count += 1
        url += '/'

https://www.linkedin.com/in/eckhard-l%C3%B6hde-68a15977/?originalSubdomain=de

















https://www.linkedin.com/in/judyvella



https://www.linkedin.com/in/kevinthomazios











https://www.linkedin.com/in/tim-jewett-a860a413

https://www.linkedin.com/in/frankekpar/?originalSubdomain=jp
https://www.linkedin.com/in/tudor-grecu-0b678013/?originalSubdomain=ro













https://www.linkedin.com/in/anthony-greene-370775b0/?trk=pub-pbmap
https://www.linkedin.com/in/sambellamy

















https://www.linkedin.com/in/kris-zarns-303a4866
https://www.linkedin.com/in/coygonrobinsoniii
https://www.linkedin.com/in/mark-olsson-1649097





https://www.linkedin.com/in/shawn-mao-b351a529


https://www.linkedin.com/in/dagane-daar-91862a51
https://www.linkedin.com/in/eddie-rafii-47a5b460


https://ca.linkedin.com/in/steve-komistek-p-eng-88a068b4














https://www.linkedin.com/in/parth-khanna-91ab30111?originalSubdomain=ca











































https://www.linkedin.com/in/sufyan-sigg-736b151



https://www.linkedin.com/in/rhyta-rounds-3a2b0632









https://www.linkedin.com/in/dennis-steffen-214a743


https://www.linkedin.com/in/charlesarmes


https://www.linkedin.com/in/jake-hauck-4b5a3b16



















https://www.linkedin.com/in/james-d-buchner-7ab83810















https://www.linkedin.com/in/madeleinewillner
https://www.linkedin.com/in/brian-viscomi-56027490


https://www.linkedin.com/in/yingjian-wang-9b721566




https://www.linkedin.com/in/nassif-rayess-6977049







https://www.linkedin.com/in/robert-flynn-3a9476



https://www.linkedin.com/in/j-snypp-5a20a24












https://www.linkedin.com/in/tillatagibson




https://www.linkedin.com/in/shuodeng


https://www.linkedin.com/in/charlie-newman-35509850
https://www.linkedin.com/in/marioviscovich



















https://www.linkedin.com/in/xiaopeng-he-84678a29














https://www.linkedin.com/in/hatamleh
https://www.linkedin.com/in/george-cancro-ba082916
















https://www.linkedin.com/in/arie-dolev-62918b5/?originalSubdomain=il


https://www.linkedin.com/in/ravi-athalye-23046a4








https://www.linkedin.com/in/peter-ripley-12b61132






https://www.linkedin.com/in/jerryedmondson
https://www.linkedin.com/in/thomas-hsueh-4b961a14


https://www.linkedin.com/in/wen-chun-huang-1511516b




https://www.linkedin.com/in/dennishanlon
https://www.linkedin.com/in/bruce-nascimbeni-20bb16150

































https://www.linkedin.com/in/winstonhenderson


https://www.linkedin.com/in/jennifer-antoine-57533076










https://www.linkedin.com/in/tarik-nabi-b3079a7
https://www.linkedin.com/in/haidar-alharbi-71389788/?originalSubdomain=kw
https://www.linkedin.com/in/chris-argiro-49464413
https://ca.linkedin.com/in/derek-herder-956ba18b
https://www.linkedin.com/in/nickfoswald





https://www.linkedin.com/in/dengguo-wu-038375141
https://www.linkedin.com/in/doron-handelman-01a2768/?locale=de_DE





https://www.linkedin.com/in/hongyu-luo-783988a










https://www.linkedin.com/in/bruce-adams-646372113/?originalSubdomain=ca






































https://www.linkedin.com/in/armen-gulian-85886b57/?locale=de_DE






























https://www.linkedin.com/in/brian-kolb-aa472a13a




































https://www.linkedin.com/in/peter-kalnay-343b8163



https://www.linkedin.com/in/ramesh-pichaiyan-41a6463

https://www.linkedin.com/in/richard-haddock-a01a1410
https://www.linkedin.com/in/mike-lucido-014936106

https://www.linkedin.com/in/kendall-saer-ford-7834673b


https://www.linkedin.com/in/nadine-kurz-52a34a9a
https://www.linkedin.com/in/nadine-kurz-52a34a9a

















https://www.linkedin.com/in/beverley-hitchins-b342b672?originalSubdomain=ca



https://www.linkedin.com/in/michel-balthazar-innovation?originalSubdomain=ca


https://www.linkedin.com/in/fraser-seymour-30303113









































https://www.linkedin.com/in/fabian-de-la-fuente-a8090b28






























































https://www.linkedin.com/in/eric-williams-7a4b9454/?trk=pub-pbmap





































https://www.linkedin.com/in/madhushree-patnaik-0bb56631






















https://www.linkedin.com/in/jim-vago
https://in.linkedin.com/in/udayankanade









https://www.linkedin.com/in/stevensliprueben












https://www.linkedin.com/in/alex-kariman
https://www.linkedin.com/in/christopher-woodsum-93a78220/zh-cn




https://www.linkedin.com/in/michellefisher1




















https://www.linkedin.com/in/vishalsh/?originalSubdomain=in






https://www.linkedin.com/in/lance-fesler-85450b5
https://www.linkedin.com/in/choon-kee-lee-b42384a4

https://www.linkedin.com/in/naraya-subramanian-1772802

In [19]:
print(count)

938